- import_playbook: fact_gatherer_playbook.yml
  tags:
    - facts

- import_playbook: aws_service_discovery_route53_playbook.yml
  tags:
    - facts

- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - playbook_vars/{{ global_var_environment }}/global_vars.yml
    - playbook_vars/{{ global_var_environment }}/application_bulkprocessor_vars.yml
    - playbook_vars/{{ global_var_environment }}/vault/{{ global_var_environment }}_variables.vault
  tasks:
    - name: Extracting ARN from service discovery
      set_fact:
        reg_bb_bulkprocessor_sd_dns_details: "{{ ServiceListJson | json_query(\"Services[?Name=='\" + global_var_services_details.bulkprocessorserver.name+\"']\") }}"

    - name: Setup || Creating ECS Cluster
      ecs_cluster:
        name: "{{ global_var_ecs_clustername }}"
        state: present
        region: "{{ global_var_ecs_region }}"
      when: global_var_ecs_clustername is defined

    - name: bb_bulkprocessor ||  Creating Parameter Store secrets
      aws_ssm_parameter_store:
        name: "{{ item.value.id }}"
        decryption: true
        region: "{{ global_var_ird_region }}"
        string_type: "SecureString"
        value: "{{ item.value.content }}"
        state: "{{ item.value.state | default('present')}}"
        overwrite_value: always # not required. choices: never;changed;always. Option to overwrite an existing value if it already exists.,String
        description: "bb_bulkprocessor param store"
      with_dict: "{{ bb_bulkprocessor_server_task_container_secretenv_definition }}"
      no_log: false
      diff: false

    # - debug: var=bb_bulkprocessor_server_task_executionRoleArn
    - name: bb_bulkprocessor || Creating bb_bulkprocessor Server task definition
      ecs_taskdefinition:
        state: present
        family: "{{ bb_bulkprocessor_server_task_family_name }}"
        region: "{{ global_var_ird_region }}"
        execution_role_arn: "{{ bb_bulkprocessor_server_task_executionRoleArn }}"
        task_role_arn: "{{ bb_bulkprocessor_server_task_executionRoleArn }}"
        network_mode: "{{ bb_bulkprocessor_server_task_networkmode }}"
        launch_type: "{{ bb_bulkprocessor_server_task_ecsmode }}"
        cpu: "{{ bb_bulkprocessor_server_task_cpu }}"
        memory: "{{ bb_bulkprocessor_server_task_memory }}"
        force_create: true
        containers:
        - name: "{{ global_var_services_details.bulkprocessorserver.name }}"
          image: "{{ bb_bulkprocessor_server_task_container_image }}"
          cpu: "{{ bb_bulkprocessor_server_task_container_cpu }}"
          memory: "{{ bb_bulkprocessor_server_task_container_memory }}"
          repositoryCredentials:
            credentialsParameter: "{{ bb_bulkprocessor_server_task_container_credentials_parameter }}"
          portMappings:
          - containerPort: "{{ global_var_services_details.bulkprocessorserver.containerPort }}"
            hostPort: "{{ global_var_services_details.bulkprocessorserver.hostPort }}"
          # - containerPort: "{{ bb_bulkprocessor_main_port }}"
          #   hostPort: "{{ bb_bulkprocessor_main_port }}"
          # - containerPort: "{{ bb_bulkprocessor_int_port }}"
          #   hostPort: "{{ bb_bulkprocessor_int_port }}"
          essential: "{{ bb_bulkprocessor_server_task_container_essential }}"
          environment: "{{ bb_bulkprocessor_server_task_container_env }}"
          secrets: "{{ bb_bulkprocessor_server_task_container_secretenv }}"
          logConfiguration:
            logDriver: "{{ bb_bulkprocessor_server_task_container_log_driver }}"
            options:
              awslogs-group: "{{ bb_bulkprocessor_server_task_container_log_logsgroup }}"
              awslogs-region: "{{ bb_bulkprocessor_server_task_container_log_logsregion }}"
              awslogs-stream-prefix: "{{ bb_bulkprocessor_server_task_container_log_logsprefix }}"

        - name: "{{ global_var_services_details.proxynginxserver.name }}"
          image: "{{global_var_services_details.proxynginxserver.image }}"
          repositoryCredentials:
            credentialsParameter: "{{ bb_bulkprocessor_server_task_container_credentials_parameter }}"
          portMappings:
          - containerPort: "{{ bb_bulkprocessor_proxyserver_listen_port }}"
            hostPort: "{{ bb_bulkprocessor_proxyserver_listen_port }}"
          essential:  "{{ bb_bulkprocessor_sidecar_server_task_container_essential }}"
          environment: "{{ bb_bulkprocessornginx_server_task_container_env }}"
          logConfiguration:
            logDriver: "{{ bb_bulkprocessor_server_task_container_log_driver }}"
            options:
              awslogs-group: "{{ bb_bulkprocessor_server_task_container_log_logsgroup }}"
              awslogs-region: "{{ bb_bulkprocessor_server_task_container_log_logsregion }}"
              awslogs-stream-prefix: "{{ bb_bulkprocessor_server_task_container_log_logsprefix }}"

        - name: "{{ bb_bulkprocessor_service_monitoringserver_name }}"
          image: "{{ bb_bulkprocessor_service_monitoringserver_image }}"
          essential: false
          secrets: "{{ bb_bulkprocessor_server_task_container_mon_secretenv }}"
          environment: "{{ bb_bulkprocessor_server_task_container_mon_env }}"
      register: reg_bb_bulkprocessor_servertaskdef


    - name: bb_bulkprocessor || Obtaining target group facts
      elb_target_group_info:
        names: "{{ bb_bulkprocessor_targetgroup_name }}"
        region: "{{ global_var_ecs_region }}"
      register: reg_bb_bulkprocessor_target_group_facts


    - name: bb_bulkprocessor || Creating bb_bulkprocessor target group public
      elb_target_group:
        name: "{{ bb_bulkprocessor_targetgroup_name }}"
        state: present
        protocol: "{{ bb_bulkprocessor_targetgroup_protocol }}"
        successful_response_codes: "{{ bb_bulkprocessor_targetgroup_success_http_code }}"
        wait_timeout: 200
        health_check_interval: "{{ bb_bulkprocessor_targetgroup_hc_interval }}"
        modify_targets: true
        healthy_threshold_count: "{{ bb_bulkprocessor_targetgroup_hc_healthycount }}"
        health_check_path: "{{ bb_bulkprocessor_targetgroup_hc_path }}"
        health_check_protocol: "{{ bb_bulkprocessor_targetgroup_hc_protocol }}"
        unhealthy_threshold_count: "{{ bb_bulkprocessor_targetgroup_hc_unhealthycount }}"
        region: "{{ global_var_ecs_region }}"
        target_type: "{{ bb_bulkprocessor_targetgroup_targettype }}"
        port: 80
        vpc_id: "{{ hostvars.localhost.reg_vpc_facts.vpcs.0.id }}"
        # wait: false
        health_check_timeout: "{{ bb_bulkprocessor_targetgroup_hc_timeout }}"
      register: reg_bb_bulkprocessor_targetgroup
      when:
      - reg_bb_bulkprocessor_target_group_facts | length == 0

    - name: Billbox Bulk Proceesor || Associating target group to a ALB listener for bulkprocessor
      shell: >
        aws elbv2 create-rule --listener-arn {{ hostvars.localhost.reg_alb_facts.load_balancers.0.listeners.0.listener_arn }}
        --priority {{ global_var_services_details.bulkprocessorserver.albPriority }}
        --conditions Field=host-header,Values={{ global_var_services_details.bulkprocessorserver.domain }}
        --actions Type=forward,TargetGroupArn={{ reg_bb_bulkprocessor_target_group_facts.target_groups.0.target_group_arn }}
        --region {{ global_var_ecs_region }}
        --profile {{ lookup('env','AWS_PROFILE') }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - not global_awx_ad_hoc_shell_switch

    - name: Billbox Bulk Processor || Associating target group to a ALB listener for bulkprocessor with awscli
      shell: >
        aws elbv2 create-rule --listener-arn {{ hostvars.localhost.reg_alb_facts.load_balancers.0.listeners.0.listener_arn }}
        --priority {{ global_var_services_details.bulkprocessorserver.albPriority }}
        --conditions Field=host-header,Values={{ global_var_services_details.bulkprocessorserver.domain }}
        --actions Type=forward,TargetGroupArn={{ reg_bb_bulkprocessor_target_group_facts.target_groups.0.target_group_arn }}
        --region {{ global_var_ecs_region }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - global_awx_ad_hoc_shell_switch
      environment:
        AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}"


    - name: bb_bulkprocessor || Creating or Updating the ECS service bb_bulkprocessor
      ecs_service:
        state: present
        name: "{{ bb_bulkprocessor_service_name }}"
        service_registries:
          - registryArn: "{{ hostvars.localhost.reg_bb_bulkprocessor_sd_dns_details.0.Arn }}"
        network_configuration:
            assign_public_ip: false
            security_groups: "{{ hostvars.localhost.reg_app_secgroup_ids_facts | list }}"
            subnets: "{{ hostvars.localhost.reg_private_app_subnet_ids_facts | list }}"
        desired_count: "{{ bb_bulkprocessor_service_count }}"
        cluster: "{{ global_var_ecs_clustername }}"
        task_definition: "{{ bb_bulkprocessor_server_task_family_name }}:{{ reg_bb_bulkprocessor_servertaskdef.taskdefinition.revision }}"
        region: "{{ global_var_ecs_region }}"
        load_balancers:
          - targetGroupArn: "{{ reg_bb_bulkprocessor_target_group_facts.target_groups.0.target_group_arn }}"
            containerName: "{{ global_var_services_details.proxynginxserver.name }}"
            containerPort: "{{ bb_bulkprocessor_proxyserver_listen_port }}"
        launch_type: "{{ bb_bulkprocessor_server_task_ecsmode }}"
        health_check_grace_period_seconds: "{{ bb_bulkprocessor_service_hc_graceperiod }}"

    - name: bb_bulkprocessor || Creating bb_bulkprocessor MEM Scalling Policy for {{ global_var_environment }}
      aws_application_scaling_policy:
        state: present
        policy_name: "{{ bb_bulkprocessor_service_mem_autoscalling_policy_name }}"
        service_namespace: ecs
        region: "{{ global_var_ecs_region }}"
        resource_id: service/{{ global_var_ecs_clustername }}/{{ bb_bulkprocessor_service_name }}
        scalable_dimension: ecs:service:DesiredCount
        policy_type: "{{ bb_bulkprocessor_service_autoscalling_policy_type }}"
        minimum_tasks: "{{ bb_bulkprocessor_service_autoscalling_min_task }}"
        maximum_tasks: "{{ bb_bulkprocessor_service_autoscalling_max_task }}"
        target_tracking_scaling_policy_configuration:
          TargetValue: "{{ bb_bulkprocessor_service_mem_autoscalling_tracking_scaling_target_value }}"
          PredefinedMetricSpecification:
            PredefinedMetricType: "{{ bb_bulkprocessor_service_mem_autoscalling_tracking_scaling_metric_spec }}"
          ScaleOutCooldown: "{{ bb_bulkprocessor_service_mem_autoscalling_tracking_scalout_cooldown }}"
          ScaleInCooldown: "{{ bb_bulkprocessor_service_mem_autoscalling_tracking_scalin_cooldown }}"

    - name: bb_bulkprocessor || Creating bb_bulkprocessor CPU Scalling Policy for {{ global_var_environment }}
      aws_application_scaling_policy:
        state: present
        policy_name: "{{ bb_bulkprocessor_service_cpu_autoscalling_policy_name }}"
        service_namespace: ecs
        region: "{{ global_var_ecs_region }}"
        resource_id: service/{{ global_var_ecs_clustername }}/{{ bb_bulkprocessor_service_name }}
        scalable_dimension: ecs:service:DesiredCount
        policy_type: "{{ bb_bulkprocessor_service_autoscalling_policy_type }}"
        minimum_tasks: "{{ bb_bulkprocessor_service_autoscalling_min_task }}"
        maximum_tasks: "{{ bb_bulkprocessor_service_autoscalling_max_task }}"
        target_tracking_scaling_policy_configuration:
          TargetValue: "{{ bb_bulkprocessor_service_cpu_autoscalling_tracking_scaling_target_value }}"
          PredefinedMetricSpecification:
            PredefinedMetricType: "{{ bb_bulkprocessor_service_cpu_autoscalling_tracking_scaling_metric_spec }}"
          ScaleOutCooldown: "{{ bb_bulkprocessor_service_cpu_autoscalling_tracking_scalout_cooldown }}"
          ScaleInCooldown: "{{ bb_bulkprocessor_service_cpu_autoscalling_tracking_scalin_cooldown }}"


    # - name: bb_bulkprocessor || Creating a Sleep Time scheduled application autoscalling for bb_bulkprocessor
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_bulkprocessor_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ bb_bulkprocessor_service_name }}-off-time
    #       --schedule "cron({{ bb_bulkprocessor_service_sleep_cron | default('00 20 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ bb_bulkprocessor_service_scheduled_sleep_autoscalling_min_task | default(0) }},MaxCapacity={{ bb_bulkprocessor_service_scheduled_sleep_autoscalling_max_task | default(0) }}
    #       --region {{ global_var_ecs_region }}
    #       --profile {{ lookup('env','AWS_PROFILE') }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - not global_awx_ad_hoc_shell_switch
    #     - bb_bulkprocessor_service_scheduled_autoscalling | default(false)
    #     - global_auto_turnoff

    # - name: bb_bulkprocessor || Creating a Sleep Time scheduled application autoscalling for bb_bulkprocessor
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_bulkprocessor_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ bb_bulkprocessor_service_name }}-off-time
    #       --schedule "cron({{ bb_bulkprocessor_service_sleep_cron | default('00 20 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ bb_bulkprocessor_service_scheduled_sleep_autoscalling_min_task | default(0) }},MaxCapacity={{ bb_bulkprocessor_service_scheduled_sleep_autoscalling_max_task | default(0) }}
    #       --region {{ global_var_ecs_region }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - global_awx_ad_hoc_shell_switch
    #     - bb_bulkprocessor_service_scheduled_autoscalling | default(false)
    #     - global_auto_turnoff
    #   environment:
    #     AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
    #     AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}"

    # - name: bb_bulkprocessor || Creating a Wake Time scheduled application autoscalling for bb_bulkprocessor
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_bulkprocessor_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ bb_bulkprocessor_service_name }}-wake-time
    #       --schedule "cron({{ bb_bulkprocessor_service_wake_cron | default('00 08 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ bb_bulkprocessor_service_scheduled_wake_autoscalling_min_task | default(1) }},MaxCapacity={{ bb_bulkprocessor_service_scheduled_wake_autoscalling_max_task | default(1) }}
    #       --region {{ global_var_ecs_region }}
    #       --profile {{ lookup('env','AWS_PROFILE') }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - not global_awx_ad_hoc_shell_switch
    #     - bb_bulkprocessor_service_scheduled_autoscalling | default(false)
    #     - global_auto_turnoff

    # - name: bb_bulkprocessor || Creating a Wake Time scheduled application autoscalling for bb_bulkprocessor
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_bulkprocessor_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ bb_bulkprocessor_service_name }}-wake-time
    #       --schedule "cron({{ bb_bulkprocessor_service_wake_cron | default('00 08 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ bb_bulkprocessor_service_scheduled_wake_autoscalling_min_task | default(1) }},MaxCapacity={{ bb_bulkprocessor_service_scheduled_wake_autoscalling_max_task | default(1) }}
    #       --region {{ global_var_ecs_region }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - global_awx_ad_hoc_shell_switch
    #     - bb_bulkprocessor_service_scheduled_autoscalling | default(false)
    #     - global_auto_turnoff
    #   environment:
    #     AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
    #     AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}"
