- import_playbook: fact_gatherer_playbook.yml
  tags:
    - facts

- import_playbook: aws_service_discovery_route53_playbook.yml
  tags:
    - facts

- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - playbook_vars/{{ global_var_environment }}/global_vars.yml
    - playbook_vars/{{ global_var_environment }}/application_core_vars.yml
    - playbook_vars/{{ global_var_environment }}/vault/{{ global_var_environment }}_variables.vault
  tasks:
    - name: Extracting ARN from service discovery
      ansible.builtin.set_fact:
        reg_core_sd_dns_details: "{{ ServiceListJson | json_query(\"Services[?Name=='\" + global_var_services_details.coreserver.name+\"']\") }}"

    - name: Setup || Creating ECS Cluster
      ecs_cluster:
        name: "{{ global_var_ecs_clustername }}"
        state: present
        region: "{{ global_var_ecs_region }}"
      when: global_var_ecs_clustername is defined

    - name: Billbox Core ||  Creating Parameter Store secrets
      aws_ssm_parameter_store:
        name: "{{ item.value.id }}"
        decryption: true
        region: "{{ global_var_ird_region }}"
        string_type: "SecureString"
        value: "{{ item.value.content }}"
        state: "{{ item.value.state | default('present') }}"
        overwrite_value: always # not required. choices: never;changed;always. Option to overwrite an existing value if it already exists.,String
        description: "bb param store"
      with_dict: "{{ bb_core_server_task_container_secretenv_definition }}"
      no_log: true
      diff: false

    # - debug: var=bb_core_server_task_executionRoleArn
    - name: Billbox Core || Creating coreServer task definition
      ecs_taskdefinition:
        state: present
        family: "{{ bb_core_server_task_family_name }}"
        region: "{{ global_var_ird_region }}"
        execution_role_arn: "{{ bb_core_server_task_executionRoleArn }}"
        task_role_arn: "{{ bb_core_server_task_executionRoleArn }}"
        network_mode: "{{ bb_core_server_task_networkmode }}"
        launch_type: "{{ bb_core_server_task_ecsmode }}"
        cpu: "{{ bb_core_server_task_cpu }}"
        memory: "{{ bb_core_server_task_memory }}"
        force_create: true
        containers:
          - name: "{{ global_var_services_details.coreserver.name }}"
            image: "{{ bb_core_server_task_container_image }}"
            cpu: "{{ bb_core_server_task_container_cpu }}"
            memory: "{{ bb_core_server_task_container_memory }}"
            repositoryCredentials:
              credentialsParameter: "{{ bb_core_server_task_container_credentials_parameter }}"
            portMappings:
              - containerPort: "{{ global_var_services_details.coreserver.containerPort }}"
                hostPort: "{{ global_var_services_details.coreserver.hostPort }}"
              - containerPort: "{{ bb_core_main_port }}"
                hostPort: "{{ bb_core_main_port }}"
              - containerPort: "{{ bb_core_int_port }}"
                hostPort: "{{ bb_core_int_port }}"
            essential: "{{ bb_core_server_task_container_essential }}"
            environment: "{{ bb_core_server_task_container_env }}"
            secrets: "{{ bb_core_server_task_container_secretenv }}"
            logConfiguration:
              logDriver: "{{ bb_core_server_task_container_log_driver }}"
              options:
                awslogs-group: "{{ bb_core_server_task_container_log_logsgroup }}"
                awslogs-region: "{{ bb_core_server_task_container_log_logsregion }}"
                awslogs-stream-prefix: "{{ bb_core_server_task_container_log_logsprefix }}"

          - name: "{{ bb_core_proxyserver_name }}"
            image: "{{ bb_core_proxyserver_image }}"
            repositoryCredentials:
              credentialsParameter: "{{ bb_core_server_task_container_credentials_parameter }}"
            portMappings:
              - containerPort: "{{ bb_core_proxyserver_listen_port }}"
                hostPort: "{{bb_core_proxyserver_listen_port }}"
            essential: "{{ bb_core_sidecar_server_task_container_essential }}"
            environment: "{{ bb_core_nginx_server_task_container_env }}"
            logConfiguration:
              logDriver: "{{ bb_core_server_task_container_log_driver }}"
              options:
                awslogs-group: "{{ bb_core_server_task_container_log_logsgroup }}"
                awslogs-region: "{{ bb_core_server_task_container_log_logsregion }}"
                awslogs-stream-prefix: "{{ bb_core_server_task_container_log_logsprefix }}"

          # - name: "{{ global_var_services_details.corenginxserver.name }}"
          #   image: "{{global_var_services_details.corenginxserver.image }}"
          #   repositoryCredentials:
          #     credentialsParameter: "{{ bb_core_server_task_container_credentials_parameter }}"
          #   portMappings:
          #     - containerPort: "{{ global_var_services_details.corenginxserver.containerPort }}"
          #       hostPort: "{{ global_var_services_details.corenginxserver.hostPort }}"
          #   essential: "{{ bb_core_sidecar_server_task_container_essential }}"
          #   environment: "{{ bb_corenginx_server_task_container_env }}"
          #   logConfiguration:
          #     logDriver: "{{ bb_core_server_task_container_log_driver }}"
          #     options:
          #       awslogs-group: "{{ bb_core_server_task_container_log_logsgroup }}"
          #       awslogs-region: "{{ bb_core_server_task_container_log_logsregion }}"
          #       awslogs-stream-prefix: "{{ bb_core_server_task_container_log_logsprefix }}"

          - name: "{{ global_var_services_details.monitoringserver.name }}"
            image: "{{ global_var_services_details.monitoringserver.image }}"
            essential: false
            secrets: "{{ bb_core_server_task_container_mon_secretenv }}"
            environment: "{{ bb_core_server_task_container_mon_env }}"

          - name: "{{ bb_core_server_sideproxy_name }}"
            image: "{{ bb_core_server_sideproxy_image }}"
            essential: "{{ bb_core_server_sideproxy_essential }}"
            repositoryCredentials:
              credentialsParameter: "{{ bb_core_server_task_container_credentials_parameter }}"
            portMappings:
              - containerPort: "{{ bb_core_server_sideproxy_admin_port }}"
                hostPort: "{{ bb_core_server_sideproxy_admin_port }}"
              - containerPort: "{{ bb_core_server_sideproxy_admin_elevy_port }}"
                hostPort: "{{ bb_core_server_sideproxy_admin_elevy_port }}"
            secrets: "{{ bb_core_server_sideproxy_secretsenv }}"
            environment: "{{ bb_core_server_sideproxy_env }}"
            logConfiguration:
              logDriver: "{{ bb_core_server_task_container_log_driver }}"
              options:
                awslogs-group: "{{ bb_core_server_task_container_log_logsgroup }}"
                awslogs-region: "{{ bb_core_server_task_container_log_logsregion }}"
                awslogs-stream-prefix: "{{ bb_core_server_task_container_log_logsprefix }}"
      register: reg_core_servertaskdef

    # - debug: var=reg_core_servertaskdef
    - name: Billbox Core || Obtaining target group facts
      elb_target_group_info:
        names: "{{ bb_core_targetgroup_name }}"
        region: "{{ global_var_ecs_region }}"
      register: reg_bb_core_target_group_facts

    # - debug: var=reg_bb_core_target_group_facts
    #   when: reg_bb_core_target_group_facts | length > 0

    - name: Billbox Core || Creating core target group public
      elb_target_group:
        name: "{{ bb_core_targetgroup_name }}"
        state: present
        protocol: "{{ bb_core_targetgroup_protocol }}"
        successful_response_codes: "{{ bb_core_targetgroup_success_http_code }}"
        wait_timeout: 200
        health_check_interval: "{{ bb_core_targetgroup_hc_interval }}"
        modify_targets: true
        healthy_threshold_count: "{{ bb_core_targetgroup_hc_healthycount }}"
        health_check_path: "{{ bb_core_targetgroup_hc_path }}"
        health_check_protocol: "{{ bb_core_targetgroup_hc_protocol }}"
        unhealthy_threshold_count: "{{ bb_core_targetgroup_hc_unhealthycount }}"
        region: "{{ global_var_ecs_region }}"
        target_type: "{{ bb_core_targetgroup_targettype }}"
        port: 80
        vpc_id: "{{ hostvars.localhost.reg_vpc_facts.vpcs.0.id }}"
        # wait: false
        health_check_timeout: "{{ bb_core_targetgroup_hc_timeout }}"
      register: reg_core_targetgroup
      when:
        - reg_bb_core_target_group_facts | length == 0

    - name: creating the alb rule condition files
      ansible.builtin.template:
        dest: "files/{{ global_var_environment }}_core_alb_conditions.json"
        src: "templates/core_alb_conditions.json"
        mode: 0644

    # - debug: var=hostvars.localhost.reg_alb_facts.load_balancers

    - name: Billbox Core || Associating public target group to a ALB listener for core
      ansible.builtin.shell: >
          aws elbv2 create-rule --listener-arn {{ hostvars.localhost.reg_alb_facts.load_balancers.0.listeners.0.listener_arn }}
          --priority {{ global_var_services_details.coreserver.albPriority }}
          --conditions file://files/{{ global_var_environment }}_core_alb_conditions.json
          --actions Type=forward,TargetGroupArn={{ reg_bb_core_target_group_facts.target_groups.0.target_group_arn }}
          --region {{ global_var_ecs_region }}
          --profile {{ lookup('env','AWS_PROFILE') }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - not global_awx_ad_hoc_shell_switch

    - name: Billbox Core || Associating public target group to a ALB listener for core
      ansible.builtin.shell: >
          aws elbv2 create-rule --listener-arn {{ hostvars.localhost.reg_alb_facts.load_balancers.0.listeners.0.listener_arn }}
          --priority {{ global_var_services_details.coreserver.albPriority }}
          --conditions file://files/{{ global_var_environment }}_core_alb_conditions.json
          --actions Type=forward,TargetGroupArn={{ reg_bb_core_target_group_facts.target_groups.0.target_group_arn }}
          --region {{ global_var_ecs_region }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - global_awx_ad_hoc_shell_switch
      environment:
        AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}"


    - name: Billbox Core || Creating or Updating the ECS service coreserver
      ecs_service:
        state: present
        name: "{{ bb_core_service_name }}"
        service_registries:
          - registryArn: "{{ hostvars.localhost.reg_core_sd_dns_details.0.Arn }}"
        network_configuration:
          assign_public_ip: true
          security_groups: "{{ hostvars.localhost.reg_app_secgroup_ids_facts | list }}"
          subnets: "{{ hostvars.localhost.reg_private_app_subnet_ids_facts | list }}"
        desired_count: "{{ bb_core_service_count }}"
        cluster: "{{ global_var_ecs_clustername }}"
        task_definition: "{{ bb_core_server_task_family_name }}:{{ reg_core_servertaskdef.taskdefinition.revision }}"
        region: "{{ global_var_ecs_region }}"
        load_balancers:
          - targetGroupArn: "{{ reg_bb_core_target_group_facts.target_groups.0.target_group_arn }}"
            containerName: "{{ global_var_services_details.corenginxserver.name }}"
            containerPort: "{{ global_var_services_details.corenginxserver.containerPort }}"
            # containerName: "{{ global_var_services_details.coreserver.name }}"
            # containerPort: "{{ global_var_services_details.coreserver.containerPort }}"
        launch_type: "{{ bb_core_server_task_ecsmode }}"
        health_check_grace_period_seconds: "{{ bb_core_service_hc_graceperiod }}"

    - name: Billbox Core ||  Ensure tags are present on service
      community.aws.ecs_tag:
        cluster_name: "{{ global_var_ecs_clustername }}"
        resource_type: service
        resource: "{{ bb_core_service_name }}"
        state: present
        region: "{{ global_var_ird_region }}"
        tags:
          Name: "{{ bb_core_service_name }}"
          ENV: "{{ global_var_environment }}"
          Product: "{{ global_var_product | capitalize }}"

    - name: Billbox Core || Creating core MEM Scalling Policy for {{ global_var_environment }}
      aws_application_scaling_policy:
        state: present
        policy_name: "{{ bb_core_service_mem_autoscalling_policy_name }}"
        service_namespace: ecs
        region: "{{ global_var_ecs_region }}"
        resource_id: service/{{ global_var_ecs_clustername }}/{{ bb_core_service_name }}
        scalable_dimension: ecs:service:DesiredCount
        policy_type: "{{ bb_core_service_autoscalling_policy_type }}"
        minimum_tasks: "{{ bb_core_service_autoscalling_min_task }}"
        maximum_tasks: "{{ bb_core_service_autoscalling_max_task }}"
        target_tracking_scaling_policy_configuration:
          TargetValue: "{{ bb_core_service_mem_autoscalling_tracking_scaling_target_value }}"
          PredefinedMetricSpecification:
            PredefinedMetricType: "{{ bb_core_service_mem_autoscalling_tracking_scaling_metric_spec }}"
          ScaleOutCooldown: "{{ bb_core_service_mem_autoscalling_tracking_scalout_cooldown }}"
          ScaleInCooldown: "{{ bb_core_service_mem_autoscalling_tracking_scalin_cooldown }}"

    - name: Billbox Core || Creating core CPU Scalling Policy for {{ global_var_environment }}
      aws_application_scaling_policy:
        state: present
        policy_name: "{{ bb_core_service_cpu_autoscalling_policy_name }}"
        service_namespace: ecs
        region: "{{ global_var_ecs_region }}"
        resource_id: service/{{ global_var_ecs_clustername }}/{{ bb_core_service_name }}
        scalable_dimension: ecs:service:DesiredCount
        policy_type: "{{ bb_core_service_autoscalling_policy_type }}"
        minimum_tasks: "{{ bb_core_service_autoscalling_min_task }}"
        maximum_tasks: "{{ bb_core_service_autoscalling_max_task }}"
        target_tracking_scaling_policy_configuration:
          TargetValue: "{{ bb_core_service_cpu_autoscalling_tracking_scaling_target_value }}"
          PredefinedMetricSpecification:
            PredefinedMetricType: "{{ bb_core_service_cpu_autoscalling_tracking_scaling_metric_spec }}"
          ScaleOutCooldown: "{{ bb_core_service_cpu_autoscalling_tracking_scalout_cooldown }}"
          ScaleInCooldown: "{{ bb_core_service_cpu_autoscalling_tracking_scalin_cooldown }}"


    - name: Billbox Core || Creating a Sleep Time scheduled application autoscalling for Billbox Core
      ansible.builtin.shell: >
          aws application-autoscaling put-scheduled-action --service-namespace ecs
          --scalable-dimension ecs:service:DesiredCount
          --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_core_service_name }}
          --scheduled-action-name scheduled-gh-office-{{ bb_core_service_name }}-off-time
          --schedule "cron({{ bb_core_service_sleep_cron | default('00 20 ? * MON-FRI *') }})"
          --scalable-target-action MinCapacity={{ bb_core_service_scheduled_sleep_autoscalling_min_task | default(0) }},MaxCapacity={{ bb_core_service_scheduled_sleep_autoscalling_max_task | default(0) }}
          --region {{ global_var_ecs_region }}
          --profile {{ lookup('env','AWS_PROFILE') }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - not global_awx_ad_hoc_shell_switch
        - bb_core_service_scheduled_autoscalling | default(false)
        - global_auto_turnoff

    - name: Billbox Core || Creating a Sleep Time scheduled application autoscalling for Billbox Core
      ansible.builtin.shell: >
          aws application-autoscaling put-scheduled-action --service-namespace ecs
          --scalable-dimension ecs:service:DesiredCount
          --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_core_service_name }}
          --scheduled-action-name scheduled-gh-office-{{ bb_core_service_name }}-off-time
          --schedule "cron({{ bb_core_service_sleep_cron | default('00 20 ? * MON-FRI *') }})"
          --scalable-target-action MinCapacity={{ bb_core_service_scheduled_sleep_autoscalling_min_task | default(0) }},MaxCapacity={{ bb_core_service_scheduled_sleep_autoscalling_max_task | default(0) }}
          --region {{ global_var_ecs_region }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - global_awx_ad_hoc_shell_switch
        - bb_core_service_scheduled_autoscalling | default(false)
        - global_auto_turnoff
      environment:
        AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}"

    - name: Billbox Core || Creating a Wake Time scheduled application autoscalling for Billbox Core
      ansible.builtin.shell: >
          aws application-autoscaling put-scheduled-action --service-namespace ecs
          --scalable-dimension ecs:service:DesiredCount
          --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_core_service_name }}
          --scheduled-action-name scheduled-gh-office-{{ bb_core_service_name }}-wake-time
          --schedule "cron({{ bb_core_service_wake_cron | default('00 08 ? * MON-FRI *') }})"
          --scalable-target-action 
          MinCapacity={{ bb_core_service_scheduled_wake_autoscalling_min_task | default(1) }},
          MaxCapacity={{ bb_core_service_scheduled_wake_autoscalling_max_task | default(1) }}
          --region {{ global_var_ecs_region }}
          --profile {{ lookup('env','AWS_PROFILE') }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - not global_awx_ad_hoc_shell_switch
        - bb_core_service_scheduled_autoscalling | default(false)
        - global_auto_turnoff

    - name: Billbox Core || Creating a Wake Time scheduled application autoscalling for Billbox Core
      ansible.builtin.shell: >
          aws application-autoscaling put-scheduled-action --service-namespace ecs
          --scalable-dimension ecs:service:DesiredCount
          --resource-id service/{{ global_var_ecs_clustername }}/{{ bb_core_service_name }}
          --scheduled-action-name scheduled-gh-office-{{ bb_core_service_name }}-wake-time
          --schedule "cron({{ bb_core_service_wake_cron | default('00 08 ? * MON-FRI *') }})"
          --scalable-target-action MinCapacity={{ bb_core_service_scheduled_wake_autoscalling_min_task | default(1) }},MaxCapacity={{ bb_core_service_scheduled_wake_autoscalling_max_task | default(1) }}
          --region {{ global_var_ecs_region }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - global_awx_ad_hoc_shell_switch
        - bb_core_service_scheduled_autoscalling | default(false)
        - global_auto_turnoff
      environment:
        AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}"
