- import_playbook: fact_gatherer_playbook.yml
  tags:
    - facts

- import_playbook: aws_service_discovery_route53_playbook.yml
  tags:
    - facts

- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - playbook_vars/{{ global_var_environment }}/global_vars.yml
    - playbook_vars/{{ global_var_environment }}/application_kowrimarketplace_vars.yml
    - playbook_vars/{{ global_var_environment }}/vault/{{ global_var_environment }}_variables.vault
  tasks:

    - name: Setup || Creating ECS Cluster
      ecs_cluster:
        name: "{{ global_var_ecs_clustername }}"
        state: present
        region: "{{ global_var_ecs_region }}"
      when: global_var_ecs_clustername is defined

    - name: KOWRI Marketplace ||  Creating Parameter Store secrets
      aws_ssm_parameter_store:
        name: "{{ item.value.id }}"
        decryption: true
        region: "{{ global_var_ird_region }}"
        string_type: "SecureString"
        value: "{{ item.value.content }}"
        state: "{{ item.value.state | default('present') }}"
        overwrite_value: always # not required. choices: never;changed;always. Option to overwrite an existing value if it already exists.,String
        description: "bb param store"
      with_dict: "{{ kowri_marketplace_server_task_container_secretenv_definition }}"
      no_log: false

    - name: KOWRI Marketplace || Creating marketplaceServer task definition
      ecs_taskdefinition:
        state: present
        family: "{{ kowri_marketplace_server_task_family_name }}"
        region: "{{ global_var_ecs_region }}"
        execution_role_arn: "{{ kowri_marketplace_server_task_executionRoleArn }}"
        network_mode: "{{ kowri_marketplace_server_task_networkmode }}"
        launch_type: "{{ kowri_marketplace_server_task_ecsmode }}"
        cpu: "{{ kowri_marketplace_server_task_cpu }}"
        memory: "{{ kowri_marketplace_server_task_memory }}"
        force_create: true
        containers:
          - name: "{{ global_var_services_details.kowrimplaceserver.name }}"
            image: "{{ kowri_marketplace_server_task_container_image }}"
            cpu: "{{ kowri_marketplace_server_task_container_cpu }}"
            memory: "{{ kowri_marketplace_server_task_container_memory }}"
            # memoryReservation: "{{ kowri_marketplace_server_task_container_memoryReservation }}"
            repositoryCredentials:
              credentialsParameter: "{{ kowri_marketplace_server_task_container_credentials_parameter }}"
            portMappings:
              - containerPort: "{{ global_var_services_details.kowrimplaceserver.containerPort }}"
                hostPort: "{{ global_var_services_details.kowrimplaceserver.hostPort }}"
            essential: "{{ kowri_marketplace_server_task_container_essential }}"
            environment: "{{ kowri_marketplace_server_task_container_env }}"
            logConfiguration:
              logDriver: "{{ kowri_marketplace_server_task_container_log_driver }}"
              options:
                awslogs-group: "{{ kowri_marketplace_server_task_container_log_logsgroup }}"
                awslogs-region: "{{ kowri_marketplace_server_task_container_log_logsregion }}"
                awslogs-stream-prefix: "{{ kowri_marketplace_server_task_container_log_logsprefix }}"

          - name: "{{ kowri_marketplace_service_reverseproxy_name }}"
            image: "{{ kowri_marketplace_service_reverseproxy_image }}"
            repositoryCredentials:
              credentialsParameter: "{{ kowri_marketplace_server_task_container_credentials_parameter }}"
            portMappings:
              - containerPort: "{{ kowri_marketplace_service_reverseproxy_container_port }}"
                hostPort: "{{ kowri_marketplace_service_reverseproxy_host_port }}"
            essential: "{{ kowri_marketplace_sidecar_server_task_container_essential }}"
            environment: "{{ kowri_marketplace_nginx_server_task_container_env }}"
            logConfiguration:
              logDriver: "{{ kowri_marketplace_server_task_container_log_driver }}"
              options:
                awslogs-group: "{{ kowri_marketplace_server_task_container_log_logsgroup }}"
                awslogs-region: "{{ kowri_marketplace_server_task_container_log_logsregion }}"
                awslogs-stream-prefix: "{{ kowri_marketplace_server_task_container_log_logsprefix }}"

          - name: "{{ kowri_marketplace_service_monitoringserver_name}}"
            image: "{{ kowri_marketplace_service_monitoringserver_image }}"
            essential: false
            secrets: "{{ kowri_marketplace_server_task_container_secretenv }}"
            environment: "{{ kowri_marketplace_server_task_container_mon_env }}"
      register: reg_marketplace_servertaskdef

    # - debug: var=reg_marketplace_servertaskdef
    - name: KOWRI Marketplace || Obtaining target group facts
      elb_target_group_info:
        names: "{{ kowri_marketplace_targetgroup_name }}"
        region: "{{ global_var_ecs_region }}"
      register: reg_kowri_marketplace_target_group_facts

    - name: KOWRI Marketplace || Creating marketplace target group
      elb_target_group:
        name: "{{ kowri_marketplace_targetgroup_name }}"
        state: present
        protocol: "{{ kowri_marketplace_targetgroup_protocol }}"
        successful_response_codes: "{{ kowri_marketplace_targetgroup_success_http_code }}"
        wait_timeout: 200
        health_check_interval: "{{ kowri_marketplace_targetgroup_hc_interval }}"
        modify_targets: true
        healthy_threshold_count: "{{ kowri_marketplace_targetgroup_hc_healthycount }}"
        health_check_path: "{{ kowri_marketplace_targetgroup_hc_path }}"
        health_check_protocol: "{{ kowri_marketplace_targetgroup_hc_protocol }}"
        unhealthy_threshold_count: "{{ kowri_marketplace_targetgroup_hc_unhealthycount }}"
        region: "{{ global_var_ecs_region }}"
        target_type: "{{ kowri_marketplace_targetgroup_targettype }}"
        port: 80
        vpc_id: "{{ hostvars.localhost.reg_vpc_facts.vpcs.0.id }}"
        # wait: false
        health_check_timeout: "{{ kowri_marketplace_targetgroup_hc_timeout }}"
      register: reg_marketplace_targetgroup
      when:
        - reg_kowri_marketplace_target_group_facts.target_groups | length == 0

    - name: KOWRI Marketplace || Second target group facts
      elb_target_group_info:
        names: "{{ kowri_marketplace_targetgroup_name }}"
        region: "{{ global_var_ecs_region }}"
      register: reg_kowri_marketplace_target_group_facts

    - name: KOWRI Marketplace || Associating target group to a ALB listener for marketplace
      shell: >
          aws elbv2 create-rule --listener-arn {{ hostvars.localhost.reg_alb_facts.load_balancers.0.listeners.0.listener_arn }}
          --priority {{ global_var_services_details.kowrimplaceserver.albPriority }}
          --conditions Field=host-header,Values={{ global_var_services_details.kowrimplaceserver.domain }}
          --actions Type=forward,TargetGroupArn={{ reg_kowri_marketplace_target_group_facts.target_groups.0.target_group_arn }}
          --region {{ global_var_ecs_region }}
          --profile {{ lookup('env','AWS_PROFILE') }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - not global_awx_ad_hoc_shell_switch

    - name: KOWRI Marketplace || Associating target group to a ALB listener for marketplace with awscli
      shell: >
          aws elbv2 create-rule --listener-arn {{ hostvars.localhost.reg_alb_facts.load_balancers.0.listeners.0.listener_arn }}
          --priority {{ global_var_services_details.kowrimplaceserver.albPriority }}
          --conditions Field=host-header,Values={{ global_var_services_details.kowrimplaceserver.domain }}
          --actions Type=forward,TargetGroupArn={{ reg_kowri_marketplace_target_group_facts.target_groups.0.target_group_arn }}
          --region {{ global_var_ecs_region }}
      when:
        - global_awx_ad_hoc_shell_switch is defined
        - global_awx_ad_hoc_shell_switch
      environment:
        AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}" 

    - name: KOWRI Marketplace || Creating or Updating the ECS service marketplaceserver
      ecs_service:
        state: present
        name: "{{ kowri_marketplace_service_name }}"
        # service_registries:
        #   - registryArn: "{{ hostvars.localhost.reg_marketplace_sd_dns_details.0.Arn }}"
        network_configuration:
            assign_public_ip: false
            security_groups: "{{ hostvars.localhost.reg_app_secgroup_ids_facts | list }}"
            subnets: "{{ hostvars.localhost.reg_private_app_subnet_ids_facts | list }}"
        desired_count: "{{ kowri_marketplace_service_count }}"
        cluster: "{{ global_var_ecs_clustername }}"
        task_definition: "{{ kowri_marketplace_server_task_family_name }}:{{ reg_marketplace_servertaskdef.taskdefinition.revision }}"
        region: "{{ global_var_ecs_region }}"
        load_balancers:
          - targetGroupArn: "{{ reg_kowri_marketplace_target_group_facts.target_groups.0.target_group_arn }}"
            # containerName: "{{ global_var_services_details.kowrimplaceserver.name }}"
            # containerPort: "{{ global_var_services_details.kowrimplaceserver.hostPort }}"
            containerName: "{{ kowri_marketplace_service_reverseproxy_name }}"
            containerPort: "{{ kowri_marketplace_service_reverseproxy_host_port }}"
        launch_type: "{{ kowri_marketplace_server_task_ecsmode }}"
        health_check_grace_period_seconds: "{{ kowri_marketplace_service_hc_graceperiod }}"

    - name: KOWRI Marketplace || Creating marketplace MEM Scalling Policy for {{ global_var_environment }}
      aws_application_scaling_policy:
        state: present
        policy_name: "{{ kowri_marketplace_service_mem_autoscalling_policy_name }}"
        service_namespace: ecs
        region: "{{ global_var_ecs_region }}"
        resource_id: service/{{ global_var_ecs_clustername }}/{{ kowri_marketplace_service_name }}
        scalable_dimension: ecs:service:DesiredCount
        policy_type: "{{ kowri_marketplace_service_autoscalling_policy_type }}"
        minimum_tasks: "{{ kowri_marketplace_service_autoscalling_min_task }}"
        maximum_tasks: "{{ kowri_marketplace_service_autoscalling_max_task }}"
        target_tracking_scaling_policy_configuration:
          TargetValue: "{{ kowri_marketplace_service_mem_autoscalling_tracking_scaling_target_value }}"
          PredefinedMetricSpecification:
            PredefinedMetricType: "{{ kowri_marketplace_service_mem_autoscalling_tracking_scaling_metric_spec }}"
          ScaleOutCooldown: "{{ kowri_marketplace_service_mem_autoscalling_tracking_scalout_cooldown }}"
          ScaleInCooldown: "{{ kowri_marketplace_service_mem_autoscalling_tracking_scalin_cooldown }}"

    - name: KOWRI Marketplace || Creating marketplace CPU Scalling Policy for {{ global_var_environment }}
      aws_application_scaling_policy:
        state: present
        policy_name: "{{ kowri_marketplace_service_cpu_autoscalling_policy_name }}"
        service_namespace: ecs
        region: "{{ global_var_ecs_region }}"
        resource_id: service/{{ global_var_ecs_clustername }}/{{ kowri_marketplace_service_name }}
        scalable_dimension: ecs:service:DesiredCount
        policy_type: "{{ kowri_marketplace_service_autoscalling_policy_type }}"
        minimum_tasks: "{{ kowri_marketplace_service_autoscalling_min_task }}"
        maximum_tasks: "{{ kowri_marketplace_service_autoscalling_max_task }}"
        target_tracking_scaling_policy_configuration:
          TargetValue: "{{ kowri_marketplace_service_cpu_autoscalling_tracking_scaling_target_value }}"
          PredefinedMetricSpecification:
            PredefinedMetricType: "{{ kowri_marketplace_service_cpu_autoscalling_tracking_scaling_metric_spec }}"
          ScaleOutCooldown: "{{ kowri_marketplace_service_cpu_autoscalling_tracking_scalout_cooldown }}"
          ScaleInCooldown: "{{ kowri_marketplace_service_cpu_autoscalling_tracking_scalin_cooldown }}"


    # - name: KOWRI Marketplace || Creating a Sleep Time scheduled application autoscalling for Billbox Marketplace
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ kowri_marketplace_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ kowri_marketplace_service_name }}-off-time
    #       --schedule "cron({{ kowri_marketplace_service_sleep_cron | default('00 20 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ kowri_marketplace_service_scheduled_sleep_autoscalling_min_task | default(0) }},MaxCapacity={{ kowri_marketplace_service_scheduled_sleep_autoscalling_max_task | default(0) }}
    #       --region {{ global_var_ecs_region }}
    #       --profile {{ lookup('env','AWS_PROFILE') }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - not global_awx_ad_hoc_shell_switch
    #     - kowri_marketplace_service_scheduled_autoscalling | default(false)    

    # - name: Billbox Marketplace Server || Creating a Sleep Time scheduled application autoscalling for Billbox Marketplace with awscli
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ kowri_marketplace_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ kowri_marketplace_service_name }}-off-time
    #       --schedule "cron({{ kowri_marketplace_service_sleep_cron | default('00 20 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ kowri_marketplace_service_scheduled_sleep_autoscalling_min_task | default(0) }},MaxCapacity={{ kowri_marketplace_service_scheduled_sleep_autoscalling_max_task | default(0) }}
    #       --region {{ global_var_ecs_region }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - global_awx_ad_hoc_shell_switch
    #     - kowri_marketplace_service_scheduled_autoscalling | default(false)
    #   environment:
    #     AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
    #     AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}" 

    # - name: KOWRI Marketplace || Creating a Wake Time scheduled application autoscalling for Billbox Marketplace
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ kowri_marketplace_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ kowri_marketplace_service_name }}-wake-time
    #       --schedule "cron({{ kowri_marketplace_service_wake_cron | default('00 08 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ kowri_marketplace_service_scheduled_wake_autoscalling_min_task | default(1) }},MaxCapacity={{ kowri_marketplace_service_scheduled_wake_autoscalling_max_task | default(1) }}
    #       --region {{ global_var_ecs_region }}
    #       --profile {{ lookup('env','AWS_PROFILE') }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - not global_awx_ad_hoc_shell_switch
    #     - kowri_marketplace_service_scheduled_autoscalling | default(false)    

    # - name: Billbox Marketplace Server || Creating a Wake Time scheduled application autoscalling for Billbox Marketplace with awscli
    #   shell: > 
    #       aws application-autoscaling put-scheduled-action --service-namespace ecs
    #       --scalable-dimension ecs:service:DesiredCount
    #       --resource-id service/{{ global_var_ecs_clustername }}/{{ kowri_marketplace_service_name }}
    #       --scheduled-action-name scheduled-gh-office-{{ kowri_marketplace_service_name }}-wake-time
    #       --schedule "cron({{ kowri_marketplace_service_wake_cron | default('00 08 ? * MON-FRI *') }})"
    #       --scalable-target-action MinCapacity={{ kowri_marketplace_service_scheduled_wake_autoscalling_min_task | default(1) }},MaxCapacity={{ kowri_marketplace_service_scheduled_wake_autoscalling_max_task | default(1) }}
    #       --region {{ global_var_ecs_region }}
    #   when:
    #     - global_awx_ad_hoc_shell_switch is defined
    #     - global_awx_ad_hoc_shell_switch
    #     - kowri_marketplace_service_scheduled_autoscalling | default(false)
    #   environment:
    #     AWS_ACCESS_KEY_ID: "{{ vault_aws_access_key }}"
    #     AWS_SECRET_ACCESS_KEY: "{{ vault_aws_access_secret }}" 
