---
- import_playbook: fact_gatherer_playbook.yml
  tags:
    - facts

- hosts: "tag_Name_{{ global_var_country_code }}_{{ global_var_product }}_{{ global_var_environment }}_jumpbox"
  become: True
  gather_facts: true
  user: "{{ global_var_ubuntu_user }}"
  vars_files:
#  - "playbook_vars/{{ global_var_environment }}/aws_users_mysql_vars.yml"
  - "playbook_vars/{{ global_var_environment }}/users_mysql_vars.yml"
  - "playbook_vars/{{ global_var_environment }}/vault/{{ global_var_environment }}_variables.vault"
  - "playbook_vars/{{ global_var_environment }}/global_vars.yml"
  tasks:

    - name: Insall Mysql Dependencies
      apt:
       pkg: "{{ jumpbox_mysql_create_user_dependencies_apps_list }}"
       
    - name: Create Users for Apps
      mysql_user:
        name: "{{ item.app_username }}"
        password: "{{ item.app_password }}"
        priv: "{{ item.db_name }}.*:{{ item.db_privileges | default('ALL,GRANT') }}"
        state: present
        host: "%"
        login_user: "{{ item.root_username }}"
        login_password: "{{ item.root_password }}"
        login_host: "{{ item.db_host }}"
        login_port: "{{ item.db_port }}"
      with_items: "{{ jumpbox_mysql_create_user_details | default({}) }}"
      when: jumpbox_mysql_create_user_details is defined
      # no_log: true