
bb_config_server_enabled: true
bb_active_region: "{{ global_var_ird_region }}"
bb_active_priv_dns_namespace: "{{ global_var_priv_dns_namespace }}"
bb_config_server_task_family_name: "{{ global_var_country_code }}-{{ global_var_product }}-{{global_var_environment}}-{{ global_var_services_details.configserver.name }}"
bb_config_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
bb_config_server_task_networkmode: awsvpc
bb_config_server_task_ecsmode: FARGATE
bb_config_server_task_cpu: 256
bb_config_server_task_memory: 1024
bb_config_server_task_container_name: "{{ global_var_services_details.configserver.name }}"
bb_config_server_task_container_image: "{{ global_var_services_details.configserver.image }}"
bb_config_server_task_container_cpu: 256
bb_config_server_task_container_memory: 1024
bb_config_server_task_container_memoryReservation: 256
bb_config_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_config_server_task_container_essential: true
bb_config_server_task_container_java_vars: 
# - "-Deureka.instance.hostname={{ global_var_services_details.configserver.name }}.{{ bb_active_priv_dns_namespace }}"
- "-Dspring.cloud.client.hostname={{ global_var_services_details.configserver.name }}.{{ bb_active_priv_dns_namespace }}"
- "-Dspring.cloud.config.server.git.uri=/opt/configrepo/"
- "-Dspring.profiles.active={{ global_var_environment }}"
# - "-Dspring.cloud.config.profile={{ global_var_environment }},mysql-{{ global_var_environment }}"
- "-Dspring.cloud.config.profile={{ global_var_environment }}"
- "-Dspring.cloud.config.server.git.search-paths={{ global_var_configserver_folder }}"
- "-Dserver.port={{ global_var_services_details.configserver.hostPort }}"
# - "-Deureka.instance.prefer-ip-address=false"
- "-DLOGENTRIES_TOKEN={{ global_var_services_details.configserver.logToken }}"
- "-Dlogging.level.root=INFO"
bb_config_server_task_container_secretenv_definition:
  git_cred:
    id: "{{ global_var_environment }}_GIT_CRED"
    name: GIT_CRED
    content: "{{ vault_git_username }}:{{ vault_git_token }}"
  dd_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
  encrypt_key:
    id: "{{ global_var_environment }}_ENCRYPT_KEY"
    name: ENCRYPT_KEY
    content: "{{ vault_configserver_encryption_key }}"
bb_config_server_task_container_secretenv:
  - name: "{{bb_config_server_task_container_secretenv_definition.git_cred.name}}"
    valueFrom: "{{ bb_config_server_task_container_secretenv_definition.git_cred.id }}"
  - name: "{{bb_config_server_task_container_secretenv_definition.dd_api_key.name}}"
    valueFrom: "{{ bb_config_server_task_container_secretenv_definition.dd_api_key.id }}"
  - name: "{{bb_config_server_task_container_secretenv_definition.encrypt_key.name}}"
    valueFrom: "{{ bb_config_server_task_container_secretenv_definition.encrypt_key.id }}"
bb_config_server_task_container_env: 
  - name: JAVA_VARS
    value: "{{ bb_config_server_task_container_java_vars | join(' ') }}"
  - name: GIT_URL
    value: "{{ global_var_configuration_git_details[0].repo_url }}"
bb_config_server_datadog_task_container_env:
  - name: ECS_FARGATE
    value: "true"
  - name: DD_APM_ENABLED
    value: "true"   
bb_config_server_task_container_log_driver: awslogs
bb_config_server_task_container_log_logsgroup: "{{ global_var_log_group }}"
bb_config_server_task_container_log_logsregion: "{{ bb_active_region }}"
bb_config_server_task_container_log_logsprefix: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-"
bb_config_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
bb_config_service_name: "{{global_var_country_code}}-{{global_var_product}}-{{global_var_environment}}-{{ global_var_services_details.configserver.name }}-service"
# bb_config_targetgroup_name: "configTG"
# bb_config_targetgroup_protocol: "http"
# bb_config_targetgroup_success_http_code: 200
# bb_config_targetgroup_hc_interval: 6
# bb_config_targetgroup_hc_timeout: 5
# bb_config_targetgroup_hc_healthycount: 3
# bb_config_targetgroup_hc_unhealthycount: 3
# bb_config_targetgroup_hc_path: "/"
# bb_config_targetgroup_hc_protocol: "http"
# bb_config_targetgroup_targettype: "ip"

bb_config_service_count: 1
bb_config_service_platform_version: 1.3.0
# bb_config_s÷ervice_hc_graceperiod: 300
bb_config_service_awscli_enabled: false
bb_config_service_wake_cron: "10 04 ? * MON-FRI *"
bb_config_service_sleep_cron: "59 21 ? * MON-FRI *"