bb_webpos_server_credentials: ' {"slydepay":{"username":"{{ vault_webposapi_username }}","password":"{{ vault_webposapi_password }}"},"billboxciv":{"username":"{{ vault_webposapi_username }}","password":"{{ vault_webposapi_password }}"},"billbox":{"username":"{{ vault_webposapi_username }}","password":"{{ vault_webposapi_password }}"},"billboxga":{"username":"bills@smartgrid.one","password":"password"},"slydepayzw":{"username":"{{ vault_webposapi_username }}","password":"password"},"kowri":{"username": "{{ vault_webpos_kowri_api_username }}", "password": "{{ vault_webpos_kowri_api_password }}"},"kowriciv":{"username": "{{ vault_webpos_kowriciv_api_username }}","password": "{{  vault_webpos_kowriciv_api_password }}"}}'
bb_webpos_server_task_family_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.webposserver.name }}"
bb_webpos_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
bb_webpos_server_task_networkmode: awsvpc
bb_webpos_server_task_ecsmode: FARGATE
bb_webpos_server_task_cpu: 256
bb_webpos_server_task_memory: 512
bb_webpos_server_task_container_name: "{{ global_var_services_details.webposserver.name }}"
bb_webpos_server_task_container_image: "{{ global_var_services_details.webposserver.image }}"
bb_webpos_server_task_container_cpu: 256
bb_webpos_server_task_container_memory: 512
bb_webpos_sidecar_server_task_container_essential: true
bb_webpos_sidecar_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_quayio_secrets_facts.ARN }}"
# bb_webpos_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_nexus_secrets_facts.ARN }}"
bb_webpos_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_webpos_server_task_container_essential: true
bb_webpos_server_task_container_env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "{{ global_var_services_details.webposserver.containerPort }}"
  - name: API
    value: "http://{{ global_var_services_details.posapiserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.posapiserver.hostPort }}"
  # - name: API_ACCESS
  #   value: '{"slydepay":{"username":"stanbic","password":"password"},"billboxciv":{"username":"nelly","password":"password"},"billbox":{"username":"slyde_integrator","password":"password"},"billboxga":{"username":"bills@smartgrid.one","password":"password"},"slydepayzw":{"username":"nelly","password":"password"}}'
  - name: BT_MAX_REQUEST_RETRIES
    value: "5"
  - name: BT_MIN_REQUEST_LOCKOUT
    value: "600000"
  - name: BT_MAX_REQUEST_LOCKOUT
    value: "3600000"
  - name: CAPTCHA_SECRET_KEY
    value: 6LejK9kZAAAAAEiy5Vdwl9nnpi0_IW-fZGg9YEhZ
  - name: "LOGENTRIES_TOKEN"
    value: "d2e5193b-a32e-411a-80f9-12393c97fa74"    
bb_webposnginx_server_task_container_env:
  - name: FULL_GIT_URL
    value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/kb-nginx-configuration.git"
  - name: CONF_FILE
    value: "webposserver_prod.conf"
bb_webpos_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    value: ' {"ENVIRONMENT":"{{ global_var_environment }}"}'
  - name: "DD_APM_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  - name: "DD_APM_ENABLED"
    value: "true"
  - name: "DD_PROCESS_AGENT_ENABLED"
    value: "true" 
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  - name: "DD_APM_RECEIVER_PORT"
    value: "8126"
bb_webpos_server_task_container_secretenv_definition:
  # mon_apm_key:
  #   id: "{{ global_var_environment }}_NEW_RELIC_LICENSE_KEY"
  #   name: NEW_RELIC_LICENSE_KEY
  #   content: "{{ vault_newrelic_license_key }}"
  mon_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
  # apm_key:
  webpoapi:
    id: "{{ global_var_environment }}_API_ACCESS"
    content: "{{ bb_webpos_server_credentials }}"
    name: API_ACCESS
bb_webpos_server_task_container_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
  - valueFrom: "{{ global_var_environment }}_API_ACCESS"
    name: API_ACCESS
bb_webpos_server_task_container_mon_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
bb_webpos_server_task_container_log_driver: awslogs
bb_webpos_server_task_container_log_logsgroup: "{{ global_var_log_group }}"
bb_webpos_server_task_container_log_logsregion: "{{ global_var_ecs_region }}"
bb_webpos_server_task_container_log_logsprefix: "{{ global_var_product }}-{{ global_var_environment }}-"
bb_webpos_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
bb_webpos_service_name: "{{ bb_webpos_server_task_family_name }}-service"
bb_webpos_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.webposserver.application_name }}TG"
bb_webpos_targetgroup_protocol: "http"
bb_webpos_targetgroup_success_http_code: 200
bb_webpos_targetgroup_hc_interval: 6
bb_webpos_targetgroup_hc_timeout: 5
bb_webpos_targetgroup_hc_healthycount: 3
bb_webpos_targetgroup_hc_unhealthycount: 3
bb_webpos_targetgroup_hc_path: "/"
bb_webpos_targetgroup_hc_protocol: "http"
bb_webpos_targetgroup_targettype: "ip"
bb_webpos_service_count: 1
bb_webpos_service_platform_version: 1.3.0
bb_webpos_service_hc_graceperiod: 600
bb_webpos_service_autoscalling_policy_type: "TargetTrackingScaling"
bb_webpos_service_autoscalling_min_task: 1
bb_webpos_service_autoscalling_max_task: 3
bb_webpos_service_mem_autoscalling_policy_name: "{{ bb_webpos_server_task_family_name }}-mem-as-policy"
bb_webpos_service_cpu_autoscalling_policy_name: "{{ bb_webpos_server_task_family_name }}-cpu-as-policy"
bb_webpos_service_mem_autoscalling_tracking_scaling_target_value: 80
bb_webpos_service_cpu_autoscalling_tracking_scaling_target_value: 50
bb_webpos_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
bb_webpos_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
bb_webpos_service_mem_autoscalling_tracking_scalout_cooldown: 60
bb_webpos_service_mem_autoscalling_tracking_scalin_cooldown: 60
bb_webpos_service_cpu_autoscalling_tracking_scalout_cooldown: 120
bb_webpos_service_cpu_autoscalling_tracking_scalin_cooldown: 180
bb_webpos_service_awscli_enabled: false
bb_webpos_service_monitoringserver_name: "datadog-agent"
bb_webpos_service_monitoringserver_image: "datadog/agent:latest"
# bb_webpos_service_scheduled_autoscalling: true
# bb_webpos_service_wake_cron: "00 12 ? * MON-FRI *"
# bb_webpos_service_sleep_cron: "59 23 ? * MON-FRI *"