---
proxy_forward_zw_econet_vhost_file: "forward_zw_econet.conf"
proxy_forward_zw_econet_log_access_file: "/var/log/nginx/forward_zw_econet_nginx_proxy_access.log"
proxy_forward_zw_econet_log_error_file: "/var/log/nginx/forward_zw_econet_nginx_proxy_error.log"
forward_zw_econet_upstream_postpaid_host1: "192.168.51.168:9081"
forward_zw_econet_upstream_data_host1: "10.10.11.90:7021"
# forward_zw_econet_upstream_postpaid_host1_mon_host1: "payonline.econet.co.zw/ecocashGateway/payment/v1/transactions/amount"
forward_zw_econet_upstream_postpaid_host1_mon_type: tcp
forward_zw_econet_upstream_postpaid_host1_mon_scheme: http
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_zw_econet:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_forward_zw_econet_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_forward_zw_econet_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ proxy_forward_zw_econet_log_access_file }}"
    access_format: "jsonlog"
    error_log_file: "{{ proxy_forward_zw_econet_log_error_file }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/postpaid/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ forward_zw_econet_upstream_postpaid_host1_mon_scheme}}://{{ forward_zw_econet_upstream_postpaid_host1 }}/"
      - context: "/data/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ forward_zw_econet_upstream_postpaid_host1_mon_scheme}}://{{ forward_zw_econet_upstream_data_host1 }}/"
webserverfamily_nginx_deletefiles_details:
  - "/etc/nginx/sites-enabled/default"
webserverfamily_nginx_common_enable_sites_details_hash:
  forward_zw_econet:
    vhost: "{{ proxy_forward_zw_econet_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  forward_zw_econet:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/forward_zw_econet.yml"
      type: "{{ forward_zw_econet_upstream_postpaid_host1_mon_type }}"
      name: "forward_zw_econet"
      enabled: true
      schedule: "@every 30s"
      hosts: ["{{ forward_zw_econet_upstream_postpaid_host1 }},{{ forward_zw_econet_upstream_data_host1 }}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"
monitoringfamily_r7insightops_forward_zw_econet_accesslog_name: "NginxProxy_Forward_ZW_Econet_Access_log"
monitoringfamily_r7insightops_forward_zw_econet_errorlog_name: "NginxProxy_Forward_ZW_Econet_Error_log"
monitoringfamily_r7insightops_agent_templating_details:
  api_key: "{{ vault_rapid7insightops_apikey }}"
  servername: "{{ inventory_hostname }}"
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  src: "rapid7_insightops/config.j2"
monitoringfamily_r7insightops_agent_templating_data:
  forward_zw_econet:
      appnginxaccess:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_zw_econet_accesslog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_zw_econet_accesslog_name }}"
        path: "{{ proxy_forward_zw_econet_log_access_file }}"
      appnginxerror:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_zw_econet_errorlog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_zw_econet_errorlog_name }}"
        path: "{{ proxy_forward_zw_econet_log_error_file }}"