---
proxy_forward_gh_mtnfttxbundle_vhost_file: "forward_gh_mtnfttxbundle.conf"
proxy_forward_gh_mtnfttxbundle_log_access_file: "/var/log/nginx/forward_gh_mtnfttxbundle_nginx_proxy_access.log"
proxy_forward_gh_mtnfttxbundle_log_error_file: "/var/log/nginx/forward_gh_mtnfttxbundle_nginx_proxy_error.log"
proxy_forward_gh_mtnfttxbundle_upstream_host1: "10.139.14.96:9099"
proxy_forward_gh_mtnfttxbundle_upstream_host1_mon_type: tcp
proxy_forward_gh_mtnfttxbundle_upstream_host1_mon_scheme: http
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_proxy_forward_gh_mtnfttxbundle:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_forward_gh_mtnfttxbundle_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_proxy_forward_gh_mtnfttxbundle_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ proxy_forward_gh_mtnfttxbundle_log_access_file }}"
    access_format: "jsonlog"
    error_log_file: "{{ proxy_forward_gh_mtnfttxbundle_log_error_file }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ proxy_forward_gh_mtnfttxbundle_upstream_host1_mon_scheme }}://{{ proxy_forward_gh_mtnfttxbundle_upstream_host1 }}/"

webserverfamily_nginx_deletefiles_hash_details:
  proxy_forward_gh_mtnfttxbundle_siteavailable:
    file: "/etc/nginx/sites-available/forward_ghmtn_fttxbundle.conf"
  proxy_forward_gh_mtn_fttxbundle_siteavailable:
    file: "/etc/nginx/sites-available/forward_gh_mtn_fttxbundle.conf"
  proxy_forward_gh_mtnfttxbundle_siteenabled:
    file: "/etc/nginx/sites-enabled/forward_ghmtn_fttxbundle.conf"
  proxy_forward_gh_mtn_fttxbundle_siteenabled:
    file: "/etc/nginx/sites-enabled/forward_gh_mtn_fttxbundle.conf"
webserverfamily_nginx_common_enable_sites_details_hash:
  proxy_forward_gh_mtnfttxbundle:
    vhost: "{{ proxy_forward_gh_mtnfttxbundle_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  proxy_forward_gh_mtnfttxbundle:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/proxy_forward_gh_mtnfttxbundle.yml"
      type: "{{ proxy_forward_gh_mtnfttxbundle_upstream_host1_mon_type }}"
      name: "proxy_forward_gh_mtnfttxbundle"
      enabled: true
      schedule: "@every 30s"
      hosts: ["{{proxy_forward_gh_mtnfttxbundle_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"
monitoringfamily_r7insightops_forward_gh_mtnfttxbundle_accesslog_name: "NginxProxy_Forward_GH_MTNFttxbundle_Access_log"
monitoringfamily_r7insightops_forward_gh_mtnfttxbundle_errorlog_name: "NginxProxy_Forward_GH_MTNFttxbundle_Error_log"
monitoringfamily_r7insightops_agent_templating_details:
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  src: "rapid7_insightops/config.j2"
  api_key: "{{ vault_rapid7insightops_apikey }}"
  servername: "{{ inventory_hostname }}"
monitoringfamily_r7insightops_agent_templating_data:
  forward_gh_mtnfttxbundle:
      appnginxaccess:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_mtnfttxbundle_accesslog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_mtnfttxbundle_accesslog_name }}"
        path: "{{ proxy_forward_gh_mtnfttxbundle_log_access_file }}"
      appnginxerror:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_mtnfttxbundle_errorlog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_mtnfttxbundle_errorlog_name }}"
        path: "{{ proxy_forward_gh_mtnfttxbundle_log_error_file }}"