
kb_webcheckout_server_enabled: true
bb_ctive_region: "{{ global_var_ird_region }}"
bb_ctive_priv_dns_namespace: "{{ global_var_priv_dns_namespace }}"
kb_webcheckout_server_task_family_name: "{{ global_var_country_code }}-{{ global_var_product }}-{{global_var_environment}}-{{ global_var_services_details.kbwebcheckoutserver.name }}"
kb_webcheckout_server_task_networkmode: awsvpc
kb_webcheckout_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
kb_webcheckout_server_task_ecsmode: FARGATE
kb_webcheckout_server_task_cpu: 256
kb_webcheckout_server_task_memory: 1024
kb_webcheckout_server_task_container_name: "{{ global_var_services_details.kbwebcheckoutserver.name }}"
kb_webcheckout_server_task_container_image: "{{ global_var_services_details.kbwebcheckoutserver.image }}"
kb_webcheckout_server_task_container_cpu: 256
kb_webcheckout_server_task_container_memory: 1024
# kb_webcheckout_server_task_container_memoryReservation: 256
# kb_webcheckout_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_quayio_secrets_facts.ARN }}"
# kb_webcheckout_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_harbor_secrets_facts.ARN }}"
kb_webcheckout_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"

kb_webcheckout_server_task_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.kbwebcheckoutserver.application_name }}TG"
kb_webcheckout_server_task_targetgroup_protocol: "http"
kb_webcheckout_server_task_targetgroup_success_http_code: 200
kb_webcheckout_server_task_targetgroup_hc_interval: 6
kb_webcheckout_server_task_targetgroup_hc_timeout: 5
kb_webcheckout_server_task_targetgroup_hc_healthycount: 3
kb_webcheckout_server_task_targetgroup_hc_unhealthycount: 3
kb_webcheckout_server_task_targetgroup_hc_path: "/actuator/health"
kb_webcheckout_server_task_targetgroup_hc_protocol: "http"
kb_webcheckout_service_hc_graceperiod: 600
# kb_webcheckout_server_task__ssl_targetgroup_hc_protocol: "https"
kb_webcheckout_server_task_targetgroup_targettype: "ip"
kb_webcheckout_proxyserver_listen_port: "80"
kb_webcheckout_proxyserver_template_name: "kb_core.conf.template"
kb_webcheckout_proxyserver_csp_values: "frame-ancestors 'none'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://ajax.googleapis.com https://fonts.googleapis.com https://www.gstatic.com https://www.google-analytics.com https://www.googletagmanager.com; font-src 'self' https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' https://www.google.com https://www.google.com.gh"
kb_webcheckout_server_task_container_essential: true
kb_webcheckout_sidecar_server_task_container_essential: true

kb_webcheckout_server_task_endpoints_enabled_by_default: false
kb_webcheckout_server_task_endpoint_health_enabled: true
kb_webcheckout_server_task_endpoint_health_show_details: "never"
kb_webcheckout_server_task_info_env_enabled: false

kb_webcheckout_server_task_container_secretenv_definition:
  mon_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
  # full_git_url:
  #   id: "{{ global_var_environment }}_FULL_GIT_URL"
  #   name: FULL_GIT_URL
  #   content: "{{ kb_webcheckout_server_task_full_groovy_git_url }}"
kb_webcheckout_server_task_container_secretenv:
  - valueFrom: "{{ global_var_environment }}_FULL_GIT_URL"
    name: FULL_GIT_URL
kb_webcheckout_server_task_container_mon_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
kb_webcheckoutnginx_server_task_container_env:
  - name: FULL_GIT_URL
    value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/kb-nginx-configuration.git"
  # - name: CONF_FILE
  #   value: "coreserver_uat.conf"
  - name: NGINX_LISTEN_PORT
    value: "{{ kb_webcheckout_proxyserver_listen_port }}"
  - name: NGINX_SERVER_HOSTNAME
    value: "{{ global_var_services_details.kbwebcheckoutserver.domain }}"
  - name: TEMPLATE_CONF_FILE
    value: "{{ kb_webcheckout_proxyserver_template_name }}"
  - name: NGINX_PROXY_PASS
    value: "localhost:{{ global_var_services_details.kbwebcheckoutserver.containerPort }}"
  - name: NGINX_ALLOW_SUBNET
    value: "{{ global_var_ird_vpc_cidr }}"
  - name: NGINX_HEADER_CSP
    value: "{{ kb_webcheckout_proxyserver_csp_values }}"
kb_webcheckout_server_task_container_env:
  - name: REACT_APP_BASEURL
    value: "https://{{ global_var_services_details.coreserver.domain}}"
  - name: REACT_APP_PORT
    value: "{{ global_var_services_details.kbwebcheckoutserver.containerPort }}"
  # - name: JAVA_VARS
  #   value: "{{ kb_webcheckout_server_task_container_java_vars | join(' ') }}"
  # - name: FULL_GIT_URL
  #   value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/uat-kb-groovy-features.git"
kb_webcheckout_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    value: ' {"ENVIRONMENT":"{{ global_var_environment }}"} '
  # - name: "DD_APM_NON_LOCAL_TRAFFIC"
  #   value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  # - name: "DD_APM_ENABLED"
  #   value: "true" 
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  # - name: "DD_APM_RECEIVER_PORT"
  #   value: "8126"

kb_webcheckout_server_task_container_log_driver: awslogs
kb_webcheckout_server_task_container_log_logsgroup: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-ecsgroup"
kb_webcheckout_server_task_container_log_logsregion: "{{ global_var_ird_region }}"
kb_webcheckout_server_task_container_log_logsprefix: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-"
kb_webcheckout_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
kb_webcheckout_service_name: "{{global_var_country_code}}-{{global_var_product}}-{{global_var_environment}}-{{ global_var_services_details.kbwebcheckoutserver.name }}-service"

kb_webcheckout_service_count: 1
kb_webcheckout_service_platform_version: 1.3.0
kb_webcheckout_service_autoscalling_policy_type: "TargetTrackingScaling"
kb_webcheckout_service_autoscalling_min_task: "{{ kb_webcheckout_service_count }}"
kb_webcheckout_service_autoscalling_max_task: 4
kb_webcheckout_service_mem_autoscalling_policy_name: "{{ kb_webcheckout_server_task_family_name }}-mem-as-policy"
kb_webcheckout_service_cpu_autoscalling_policy_name: "{{ kb_webcheckout_server_task_family_name }}-cpu-as-policy"
kb_webcheckout_service_mem_autoscalling_tracking_scaling_target_value: 70
kb_webcheckout_service_cpu_autoscalling_tracking_scaling_target_value: 50
kb_webcheckout_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
kb_webcheckout_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
kb_webcheckout_service_mem_autoscalling_tracking_scalout_cooldown: 60
kb_webcheckout_service_mem_autoscalling_tracking_scalin_cooldown: 60
kb_webcheckout_service_cpu_autoscalling_tracking_scalout_cooldown: 120
kb_webcheckout_service_cpu_autoscalling_tracking_scalin_cooldown: 180
kb_webcheckout_service_awscli_enabled: false
# kb_webcheckout_service_scheduled_autoscalling: true
# kb_webcheckout_service_wake_cron: "10 04 ? * MON-FRI *"
# kb_webcheckout_service_sleep_cron: "59 19 ? * MON-FRI *"
# kb_webcheckout_service_vars_main_base_url: "http://{{ global_var_services_details.coreserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.coreserver.containerPort }}"
# kb_webcheckout_configmap_namespace_and_port_for_messenger: "{{ global_var_services_details.messengerserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.messengerserver.containerPort }}"
# kb_webcheckout_configmap_namespace_and_port_for_templateengine: "{{ global_var_services_details.templateengineserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.templateengineserver.containerPort }}"
# kb_webcheckout_kafka_bootstrap: "{{ hostvars.localhost.reg_kafka_bootstrap_facts_ips_and_port }}"