# kb_integration_umbapi_main_port: 9595
# kb_integration_umbapi_int_port: 9191
kb_integration_umbapi_tomcat_jmx_port: 13000
kb_integration_umbapi_server_enabled: true
bb_ctive_region: "{{ global_var_ird_region }}"
bb_ctive_priv_dns_namespace: "{{ global_var_priv_dns_namespace }}"
kb_integration_umbapi_server_task_family_name: "{{ global_var_country_code }}-{{ global_var_product }}-{{global_var_environment}}-{{ global_var_services_details.kb_integration_umbapiserver.name }}"
kb_integration_umbapi_server_task_networkmode: awsvpc
kb_integration_umbapi_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
kb_integration_umbapi_server_task_ecsmode: FARGATE
kb_integration_umbapi_server_task_cpu: 256
kb_integration_umbapi_server_task_memory: 1024
kb_integration_umbapi_server_task_container_name: "{{ global_var_services_details.kb_integration_umbapiserver.name }}"
kb_integration_umbapi_server_task_container_image: "{{ global_var_services_details.kb_integration_umbapiserver.image }}"
kb_integration_umbapi_server_task_container_cpu: 256
kb_integration_umbapi_server_task_container_memory: 1024
# kb_integration_umbapi_server_task_container_memoryReservation: 256
# kb_integration_umbapi_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_quayio_secrets_facts.ARN }}"
# kb_integration_umbapi_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_harbor_secrets_facts.ARN }}"
kb_integration_umbapi_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
kb_integration_umbapi_server_task_container_essential: true
kb_integration_umbapi_sidecar_server_task_container_essential: true
kb_integration_umbapi_server_task_service_code: "10010"
kb_integration_umbapi_server_task_post_trans_url: "https://api.myumbbank.com/banking/test/v1/transaction"
kb_integration_umbapi_server_task_get_acc_bal_url: "https://api.myumbbank.com/banking/test/v1/account/balance"
kb_integration_umbapi_server_task_create_acc_url: "https://api.myumbbank.com/banking/test/v1/account"
kb_integration_umbapi_server_task_spring_application_name: "kb-integration-umb"
kb_integration_umbapi_server_task_spring_config_name: "kb-integration-umb"
kb_integration_umbapi_server_task_spring_config_url: "http://{{ global_var_services_details.configserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.configserver.hostPort }}"
kb_integration_umbapi_server_task_spring_active_profile: ""

kb_integration_umbapi_server_task_container_java_vars:
- "-XX:MaxRAM={{ kb_integration_umbapi_server_task_memory * 2|pow(20) | int}}"
- "-XX:MinRAMPercentage=40.0"
- "-XX:MaxRAMPercentage=90.0"
- "-XX:+HeapDumpOnOutOfMemoryError" 
- "-Dspring.cloud.config.uri=http://{{ global_var_services_details.configserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.configserver.hostPort }}"
- "-Dspring.application.name={{ global_var_services_details.kb_integration_umbapiserver.application_name }}"
- "-Dspring.cloud.config.name={{ global_var_services_details.kb_integration_umbapiserver.config_name }}"
- "-Dspring.cloud.config.profile={{ global_var_environment }}"
- "-Dspring.profiles.active={{ global_var_environment }}"
- "-Dserver.port={{ global_var_services_details.kb_integration_umbapiserver.containerPort }}"
- "-Dlogging.level.root=INFO" 

kb_integration_umbapi_server_task_container_secretenv_definition:
  mon_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
kb_integration_umbapi_server_task_container_mon_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
kb_integration_umbapi_server_task_container_env:
  - name: JAVA_VARS
    value: "{{ kb_integration_umbapi_server_task_container_java_vars | join(' ') }}"
kb_integration_umbapi_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    value: ' {"ENVIRONMENT":"{{ global_var_environment }}"} '
  # - name: "DD_APM_NON_LOCAL_TRAFFIC"
  #   value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  # - name: "DD_APM_ENABLED"
  #   value: "true" 
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  # - name: "DD_APM_RECEIVER_PORT"
  #   value: "8126"

kb_integration_umbapi_server_task_container_log_driver: awslogs
kb_integration_umbapi_server_task_container_log_logsgroup: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-ecsgroup"
kb_integration_umbapi_server_task_container_log_logsregion: "{{ global_var_ird_region }}"
kb_integration_umbapi_server_task_container_log_logsprefix: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-"
kb_integration_umbapi_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
kb_integration_umbapi_service_name: "{{global_var_country_code}}-{{global_var_product}}-{{global_var_environment}}-{{ global_var_services_details.kb_integration_umbapiserver.name }}-service"

kb_integration_umbapi_service_count: 1
kb_integration_umbapi_service_platform_version: 1.3.0
kb_integration_umbapi_service_autoscalling_policy_type: "TargetTrackingScaling"
kb_integration_umbapi_service_autoscalling_min_task: "{{ kb_integration_umbapi_service_count }}"
kb_integration_umbapi_service_autoscalling_max_task: 4
kb_integration_umbapi_service_mem_autoscalling_policy_name: "{{ kb_integration_umbapi_server_task_family_name }}-mem-as-policy"
kb_integration_umbapi_service_cpu_autoscalling_policy_name: "{{ kb_integration_umbapi_server_task_family_name }}-cpu-as-policy"
kb_integration_umbapi_service_mem_autoscalling_tracking_scaling_target_value: 70
kb_integration_umbapi_service_cpu_autoscalling_tracking_scaling_target_value: 50
kb_integration_umbapi_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
kb_integration_umbapi_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
kb_integration_umbapi_service_mem_autoscalling_tracking_scalout_cooldown: 60
kb_integration_umbapi_service_mem_autoscalling_tracking_scalin_cooldown: 60
kb_integration_umbapi_service_cpu_autoscalling_tracking_scalout_cooldown: 120
kb_integration_umbapi_service_cpu_autoscalling_tracking_scalin_cooldown: 180
kb_integration_umbapi_service_awscli_enabled: false
# kb_integration_umbapi_service_scheduled_autoscalling: true
# kb_integration_umbapi_service_wake_cron: "10 04 ? * MON-FRI *"
# kb_integration_umbapi_service_sleep_cron: "59 19 ? * MON-FRI *"
# kb_integration_umbapi_service_vars_main_base_url: "http://{{ global_var_services_details.coreserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.coreserver.containerPort }}"
# kb_integration_umbapi_configmap_namespace_and_port_for_messenger: "{{ global_var_services_details.messengerserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.messengerserver.containerPort }}"
# kb_integration_umbapi_configmap_namespace_and_port_for_templateengine: "{{ global_var_services_details.templateengineserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.templateengineserver.containerPort }}"
# kb_integration_umbapi_kafka_bootstrap: "{{ hostvars.localhost.reg_kafka_bootstrap_facts_ips_and_port }}"