

bb_marketplace_server_task_family_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.marketplaceserver.name }}"
bb_marketplace_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
bb_marketplace_server_task_networkmode: awsvpc
bb_marketplace_server_task_ecsmode: FARGATE
bb_marketplace_server_task_cpu: 256
bb_marketplace_server_task_memory: 512
bb_marketplace_server_task_container_name: "{{ global_var_services_details.marketplaceserver.name }}"
bb_marketplace_server_task_container_image: "{{ global_var_services_details.marketplaceserver.image }}"
bb_marketplace_server_task_container_cpu: 256
bb_marketplace_server_task_container_memory: 512
# bb_marketplace_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_aws_secrets_facts.ARN }}"
# bb_marketplace_sidecar_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_quayio_secrets_facts.ARN }}"
# bb_marketplace_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_nexus_secrets_facts.ARN }}"
# bb_marketplace_sidecar_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_marketplace_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_marketplace_server_task_container_essential: true
bb_marketplace_server_task_container_env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "{{ global_var_services_details.marketplaceserver.containerPort }}"
  - name: COL_API
    value: "http://{{ global_var_services_details.coreserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.coreserver.intPort }}"
  - name: POS_API
    value: "http://{{ global_var_services_details.posapiserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.posapiserver.hostPort }}"
  - name: COL_USERNAME
    value: "stanbic"
  - name: COL_PASSWORD
    value: "password"
  - name: POS_USERNAME
    value: "stanbic"
  - name: POS_PASSWORD
    value: "password"
  - name: BT_MAX_REQUEST_RETRIES
    value: "5"
  - name: BT_MIN_REQUEST_LOCKOUT
    value: "600000"
  - name: BT_MAX_REQUEST_LOCKOUT
    value: "3600000"
  - name: CAPTCHA_SECRET_KEY
    value: 6LcDAcoZAAAAAFxz9CS-eMvHaMO_KjuCXYOYEM5s
bb_marketplace_sidecar_server_task_container_essential: true
bb_marketplacenginx_server_task_container_env:
  - name: FULL_GIT_URL
    value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/kb-nginx-configuration.git"
  - name: CONF_FILE
    value: "marketplaceserver_uat.conf"
bb_marketplace_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    value: ' {"ENVIRONMENT":"{{ global_var_environment }}"}'
  - name: "DD_APM_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  - name: "DD_APM_ENABLED"
    value: "true" 
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  - name: "DD_APM_RECEIVER_PORT"
    value: "8126"
bb_marketplace_server_task_container_secretenv_definition:
  mon_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
bb_marketplace_server_task_container_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
bb_marketplace_server_task_container_log_driver: awslogs
bb_marketplace_server_task_container_log_logsgroup: "{{ global_var_log_group }}"
bb_marketplace_server_task_container_log_logsregion: "{{ global_var_ecs_region }}"
bb_marketplace_server_task_container_log_logsprefix: "{{ global_var_product }}-{{ global_var_environment }}-"
bb_marketplace_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
bb_marketplace_service_name: "{{ bb_marketplace_server_task_family_name }}-service"
bb_marketplace_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.marketplaceserver.application_name }}TG"
bb_marketplace_targetgroup_protocol: "http"
bb_marketplace_targetgroup_success_http_code: 200
bb_marketplace_targetgroup_hc_interval: 6
bb_marketplace_targetgroup_hc_timeout: 5
bb_marketplace_targetgroup_hc_healthycount: 3
bb_marketplace_targetgroup_hc_unhealthycount: 3
bb_marketplace_targetgroup_hc_path: "/"
bb_marketplace_targetgroup_hc_protocol: "http"
bb_marketplace_targetgroup_targettype: "ip"
bb_marketplace_service_count: 1
bb_marketplace_service_platform_version: 1.3.0
bb_marketplace_service_hc_graceperiod: 600
bb_marketplace_service_autoscalling_policy_type: "TargetTrackingScaling"
bb_marketplace_service_autoscalling_min_task: 1
bb_marketplace_service_autoscalling_max_task: 3
bb_marketplace_service_mem_autoscalling_policy_name: "{{ bb_marketplace_server_task_family_name }}-mem-as-policy"
bb_marketplace_service_cpu_autoscalling_policy_name: "{{ bb_marketplace_server_task_family_name }}-cpu-as-policy"
bb_marketplace_service_mem_autoscalling_tracking_scaling_target_value: 80
bb_marketplace_service_cpu_autoscalling_tracking_scaling_target_value: 50
bb_marketplace_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
bb_marketplace_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
bb_marketplace_service_mem_autoscalling_tracking_scalout_cooldown: 60
bb_marketplace_service_mem_autoscalling_tracking_scalin_cooldown: 60
bb_marketplace_service_cpu_autoscalling_tracking_scalout_cooldown: 120
bb_marketplace_service_cpu_autoscalling_tracking_scalin_cooldown: 180
bb_marketplace_service_awscli_enabled: false
# bb_marketplace_service_scheduled_autoscalling: false
# bb_marketplace_service_wake_cron: "00 06 ? * MON-FRI *"
# bb_marketplace_service_sleep_cron: "59 20 ? * MON-FRI *"