

bb_securecardhandler_server_enabled: true
smartgrid_active_region: "{{ global_var_ird_region }}"
smartgrid_active_priv_dns_namespace: "{{ global_var_priv_dns_namespace }}"
bb_securecardhandler_server_task_family_name: "{{ global_var_country_code }}-{{ global_var_product }}-{{global_var_environment}}-{{ global_var_services_details.securecardhandlerserver.name }}"
bb_securecardhandler_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
bb_securecardhandler_server_task_networkmode: awsvpc
bb_securecardhandler_server_task_ecsmode: FARGATE
bb_securecardhandler_server_task_cpu: 512
bb_securecardhandler_server_task_memory: 2048
bb_securecardhandler_server_task_container_name: "{{ global_var_services_details.securecardhandlerserver.name }}"
bb_securecardhandler_server_task_container_image: "{{ global_var_services_details.securecardhandlerserver.image }}"
bb_securecardhandler_server_task_container_cpu: 512
bb_securecardhandler_server_task_container_memory: 2048
bb_securecardhandler_server_task_container_memoryReservation: 256
# bb_securecardhandler_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_nexus_secrets_facts.ARN }}"
# bb_securecardhandler_sidecar_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_securecardhandler_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_securecardhandler_server_task_container_essential: true
bb_securecardhandler_sidecar_server_task_container_essential: true
bb_securecardhandler_server_task_container_java_vars: 
- "-XX:MaxRAM={{ bb_securecardhandler_server_task_memory * 2|pow(20) | int}}"
- "-XX:MinRAMPercentage=40.0"
- "-XX:MaxRAMPercentage=90.0"
- "-XX:+HeapDumpOnOutOfMemoryError" 
- "-Dspring.cloud.config.uri=http://{{ global_var_services_details.configserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.configserver.hostPort }}"
- "-Dspring.application.name={{ global_var_services_details.securecardhandlerserver.application_name }}"
- "-Dspring.cloud.config.name={{ global_var_services_details.securecardhandlerserver.config_name }}"
- "-Dspring.cloud.config.profile={{ global_var_environment }},mysql-{{ global_var_environment }},mongo-{{ global_var_environment }}"
- "-Dspring.profiles.active={{ global_var_environment }}"
- "-Dserver.port={{ global_var_services_details.securecardhandlerserver.containerPort }}"
- "-DLOGENTRIES_TOKEN={{ global_var_services_details.securecardhandlerserver.logToken }}"
- "-DVAULT_ADDR=http://127.0.0.1:8200"
- "-DVAULT_TOKEN=00000000-0000-0000-0000-000000000000"
- "-Dlogging.level.root=INFO"  
# - "-Ddd.agent.host=localhost"
# - "-Ddd.agent.port=8126"
# - "-Ddd.service={{ bb_securecardhandler_service_name }}"
# - "-Ddd.env={{ global_var_environment }}"
# - "-Ddd.version={{ global_var_services_details.securecardhandlerserver.image.split(':')[1] }}"
# - "-javaagent:/opt/datadog/dd-java-agent.jar"

bb_securecardhandler_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    value: ' {"ENVIRONMENT":"{{ global_var_environment }}"}'
  - name: "DD_APM_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  - name: "DD_APM_ENABLED"
    value: "true" 
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  - name: "DD_APM_RECEIVER_PORT"
    value: "8126"
bb_securecardhandler_server_task_container_env:
  - name: JAVA_VARS
    value: "{{ bb_securecardhandler_server_task_container_java_vars | join(' ') }}"
  - name: BB_CARD_PROXY_SERVER_CONTEXT
    value: "{{ bb_securecardhandler_context_path }}"
  - name: BB_CARD_PROXY_SERVER_PORT
    value: "{{ global_var_services_details.securecardhandlerserver.containerPort }}"
  - name: BB_CARD_PROXY_CALLBACKURL
    value: "https://billboxcore.doersops.com/integrations/callback-path/migs/DREAMOVAL"
  - name: BB_CARD_PROXY_POSAPI_BASEURL
    value: "http://{{ global_var_services_details.posapiserver.name }}.{{ global_var_priv_dns_namespace }}"
  - name: BB_CARD_PROXY_PROCESSOR_BASEURL
    value: "http://{{ global_var_services_details.cardhandlerserver.name }}.{{ global_var_priv_dns_namespace }}"
bb_securecardhandler_server_task_container_secret_rawenv:
  mon_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
bb_securecardhandler_server_task_container_mon_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY

bb_securecardhandler_server_task_container_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
bb_securecardhandler_nginx_server_task_container_env:
  - name: NGINX_LISTEN_PORT
    value: "{{ bb_securecardhandler_proxyserver_listen_port }}"
  - name: NGINX_SSL_CERT_FILE
    value: "star_doersops_com_bundle.crt"
  - name: NGINX_SSL_KEY_FILE
    value: "star_doersops_com.key"
  - name: NGINX_SSL_CA_FILE
    value: "BillboxROOTCA.crt"
  - name: NGINX_PROXY_PORT
    value: "{{ global_var_services_details.securecardhandlerserver.containerPort }}"
  - name: TEMPLATE_CONF_FILE
    value: "reverse_client_ssl.conf.template"
  - name: NGINX_SERVER_HOSTNAME
    value: "{{ global_var_services_details.securecardhandlerserver.domain }}"

bb_securecardhandler_server_task_container_log_driver: awslogs
bb_securecardhandler_server_task_container_log_logsgroup: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-ecsgroup"
bb_securecardhandler_server_task_container_log_logsregion: "{{ global_var_ird_region }}"
bb_securecardhandler_server_task_container_log_logsprefix: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-"
bb_securecardhandler_alb_arn: "{{ hostvars.localhost.reg_mtls_alb_facts.load_balancers.0.load_balancer_arn }}"
bb_securecardhandler_service_name: "{{global_var_country_code}}-{{global_var_product}}-{{global_var_environment}}-{{ global_var_services_details.securecardhandlerserver.name }}-service"
bb_securecardhandler_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.securecardhandlerserver.application_name }}TG"
bb_securecardhandler_targetgroup_protocol: "tcp"
bb_securecardhandler_targetgroup_success_http_code: 200
bb_securecardhandler_targetgroup_hc_interval: 10
bb_securecardhandler_targetgroup_hc_timeout: 5
bb_securecardhandler_targetgroup_hc_healthycount: 3
bb_securecardhandler_targetgroup_hc_unhealthycount: 3
bb_securecardhandler_targetgroup_hc_path: "{{ bb_securecardhandler_context_path }}/actuator/health"
bb_securecardhandler_targetgroup_hc_protocol: "http"
bb_securecardhandler_targetgroup_hc_port: "{{ global_var_services_details.securecardhandlerserver.containerPort }}"
bb_securecardhandler_targetgroup_targettype: "ip"

bb_securecardhandler_service_count: 1
bb_securecardhandler_service_platform_version: 1.3.0
bb_securecardhandler_service_hc_graceperiod: 600
bb_securecardhandler_service_autoscalling_policy_type: "TargetTrackingScaling"
bb_securecardhandler_service_autoscalling_min_task: "{{ bb_securecardhandler_service_count }}"
bb_securecardhandler_service_autoscalling_max_task: 3
bb_securecardhandler_service_mem_autoscalling_policy_name: "{{ bb_securecardhandler_server_task_family_name }}-mem-as-policy"
bb_securecardhandler_service_cpu_autoscalling_policy_name: "{{ bb_securecardhandler_server_task_family_name }}-cpu-as-policy"
bb_securecardhandler_service_mem_autoscalling_tracking_scaling_target_value: 70
bb_securecardhandler_service_cpu_autoscalling_tracking_scaling_target_value: 50
bb_securecardhandler_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
bb_securecardhandler_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
bb_securecardhandler_service_mem_autoscalling_tracking_scalout_cooldown: 60
bb_securecardhandler_service_mem_autoscalling_tracking_scalin_cooldown: 60
bb_securecardhandler_service_cpu_autoscalling_tracking_scalout_cooldown: 120
bb_securecardhandler_service_cpu_autoscalling_tracking_scalin_cooldown: 180
bb_securecardhandler_service_awscli_enabled: false
# bb_securecardhandler_service_wake_cron: "30 04 ? * MON-FRI *"
# bb_securecardhandler_service_sleep_cron: "59 20 ? * MON-FRI *"
# bb_securecardhandler_service_scheduled_autoscalling: false
bb_securecardhandler_proxyserver_listen_port: 443


bb_securecardhandler_transaction_url_success: "https://{{ global_var_services_details.securecardhandlerserver.domain }}/secure/card/callback/complete"
bb_securecardhandler_transaction_url_error: "https://{{ global_var_services_details.securecardhandlerserver.domain }}/secure/card/processing/error"
bb_securecardhandler_procesor: MIGS
bb_securecardhandler_redis_host: "{{ hostvars.localhost.reg_elasticache_facts }}"
bb_securecardhandler_redis_port: "{{ global_var_redis_port }}"
bb_securecardhandler_service_assign_public_ip: yes
bb_securecardhandler_server_task_container_datadog_essential: false
bb_securecardhandler_server_task_container_envoy_essential: false
bb_securecardhandler_elk_cluster_nodes: "https://{{ hostvars.localhost.reg_elasticsearch_cluster.Endpoints.vpc }}"
bb_securecardhandler_context_path: /cardapi

