
bb_securecore_main_port: 9595
bb_securecore_int_port: 9191
bb_securecore_tomcat_jmx_port: 13000
bb_securecore_server_enabled: true
bb_ctive_region: "{{ global_var_ird_region }}"
bb_ctive_priv_dns_namespace: "{{ global_var_priv_dns_namespace }}"
bb_securecore_server_task_family_name: "{{ global_var_country_code }}-{{ global_var_product }}-{{global_var_environment}}-{{ global_var_services_details.securecoreserver.name }}"
bb_securecore_server_task_networkmode: awsvpc
bb_securecore_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
bb_securecore_server_task_ecsmode: FARGATE
bb_securecore_server_task_cpu: 2048
bb_securecore_server_task_memory: 5120
bb_securecore_server_task_container_name: "{{ global_var_services_details.securecoreserver.name }}"
bb_securecore_server_task_container_image: "{{ global_var_services_details.securecoreserver.image }}"
bb_securecore_server_task_container_cpu: 2048
bb_securecore_server_task_container_memory: 5120
bb_securecore_server_task_container_memoryReservation: 1024
# bb_securecore_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_quayio_secrets_facts.ARN }}"
bb_securecore_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_securecore_server_task_container_portmap_containerport: 8080
bb_securecore_server_task_container_portmap_hostport: 8080
bb_securecore_server_task_container_essential: true
bb_securecore_sidecar_server_task_container_essential: true
bb_securecore_image_path: "{{ global_var_cloudfront_base_url }}/static/images/"
bb_securecore_download_path: "{{ global_var_cloudfront_base_url }}/download/"
bb_securecore_server_owasp_resc: classpath:*.properties
bb_securecore_server_auth_cache_ttl_mins: "10"
bb_securecore_server_max_login_attempt: "3"
bb_securecore_server_max_use_forward_headers: "true"

bb_securecore_server_task_container_java_vars:
  - "-Xmx{{ bb_securecore_server_task_container_memory }}M"
  - "-XX:PermSize=256m -XX:MaxPermSize={{ bb_securecore_server_task_container_memoryReservation }}M"
  - "-XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled"
  - "-XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
  - "-XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark"
  - "-XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M"
  - "-Dsun.net.inetaddr.ttl=300"
  - "-Djava.rmi.server.hostname=localhost"
  - "-Dcom.sun.management.jmxremote"
  - "-Dcom.sun.management.jmxremote.port={{ bb_securecore_tomcat_jmx_port }}"
  - "-Dcom.sun.management.jmxremote.ssl=False" 
  - "-Dcom.sun.management.jmxremote.authenticate=False"
  - "-Dhttps.protocols=TLSv1.2,TLSv1.3"
  - "-Djdk.tls.client.protocols=TLSv1.2,TLSv1.3"
  - "-DLOGENTRIES_TOKEN={{ global_var_services_details.securecoreserver.logToken }}"
  - "-Dauth.attempt.cache.duration.mins=10"
  - "-Dserver.use-forward-headers=false"
  - "-Ddd.agent.host=localhost"
  - "-Ddd.agent.port=8126"
  - "-Ddd.logs.injection=true"
  - "-Ddd.service={{ bb_securecore_service_name }}"
  - "-Ddd.env={{ global_var_environment }}"
  - "-Ddd.version={{ global_var_services_details.securecoreserver.image.split(':')[1] }}"
  # - "-javaagent:/opt/datadog/dd-java-agent.jar"
bb_securecore_server_task_container_secretenv_definition:
  mainport:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_APP_MAIN_PORT"
    name: BB_APP_MAIN_PORT
    content: "{{ bb_securecore_main_port }}"
  intport:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_APP_INT_PORT"
    name: BB_APP_INT_PORT
    content: "{{ bb_securecore_int_port }}"
  mongodbname:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_DBNAME"
    name: BB_MONGO_DBNAME
    content: "{{ vault_mongo_core_dbname }}"
  mongodbrepllist:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_REPL_LIST"
    name: BB_MONGO_REPL_LIST
    content: "{{ hostvars.localhost.reg_mongo_cluster_uri }}"
  mongodbusername:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_USERNAME"
    name: BB_MONGO_USERNAME
    content: "{{ vault_mongo_core_username }}"
  mongodbpassword:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_PASSWORD"
    name: BB_MONGO_PASSWORD
    content: "{{ vault_mongo_core_password }}"
  redishost:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_REDIS_HOST"
    name: BB_REDIS_HOST
    content: "{{ hostvars.localhost.reg_elasticache_facts }}"
  redisport:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_REDIS_PORT"
    name: BB_REDIS_PORT
    content: "{{ global_var_redis_port }}"
  mon_api_key:
    id: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
    content: "{{ vault_datadog_api_key }}"
  full_mongo_uri:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_URI"
    name: BB_MONGO_URI
    content: "mongodb://{{ vault_mongo_core_username }}:{{ vault_mongo_core_password }}@{{ hostvars.localhost.reg_mongo_cluster_uri }}/{{ vault_mongo_core_dbname }}?replicaSet={{ global_var_replicatset_name }}&readPreference=secondaryPreferred"
  keycloak_realm:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_REALM"
    name: BB_KEYCLOAK_REALM
    content: "{{ vault_keycloak_realm }}"
  keycloak_client_id:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENT_ID"
    name: BB_KEYCLOAK_CLIENT_ID
    content: "{{ vault_keycloak_client_id }}"
  keycloak_client_secret:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENT_SECRET"
    name: BB_KEYCLOAK_CLIENT_SECRET
    content: "{{ vault_keycloak_client_secret }}"
  keycloak_manager_user:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_MANAGER_USER"
    name: BB_KEYCLOAK_MANAGER_USER
    content: "{{ vault_keyclaok_manager_user }}"
  keycloak_manager_password:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_MANAGER_PASSWORD"
    name: BB_KEYCLOAK_MANAGER_PASSWORD
    content: "{{ vault_keycloak_manager_password }}"
  keycloak_clients_admin:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENTS_ADMIN"
    name: BB_KEYCLOAK_CLIENTS_ADMIN
    content: "{{ vault_keycloak_clients_admin }}"
  keycloak_clients_biller:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENTS_BILLER"
    name: BB_KEYCLOAK_CLIENTS_BILLER
    content: "{{ vault_keyclaok_clietns_biller }}"
  keycloak_clients_integrator:
    id: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENTS_INTEGRATOR"
    name: BB_KEYCLOAK_CLIENTS_INTEGRATOR
    content: "{{ vault_keycloak_clients_integrator }}"

bb_securecore_server_task_container_secretenv:
  - name: BB_APP_MAIN_PORT
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_APP_MAIN_PORT"
  - name: BB_APP_INT_PORT
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_APP_INT_PORT"
  - name: BB_MONGO_DBNAME
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_DBNAME"
  - name: BB_MONGO_REPL_LIST
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_REPL_LIST"
  - name: BB_MONGO_USERNAME
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_USERNAME"
  - name: BB_MONGO_PASSWORD
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_PASSWORD"
  - name: BB_REDIS_HOST
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_REDIS_HOST"
  - name: BB_REDIS_PORT
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_REDIS_PORT"
  # - name: NEW_RELIC_LICENSE_KEY
  #   valueFrom: "{{ global_var_environment }}_NEW_RELIC_LICENSE_KEY"
  - name: BB_MONGO_URI
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_MONGO_URI"
  - name: BB_KEYCLOAK_REALM
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_REALM"
  - name: BB_KEYCLOAK_CLIENT_ID
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENT_ID"
  - name: BB_KEYCLOAK_CLIENT_SECRET
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENT_SECRET"
  - name: BB_KEYCLOAK_MANAGER_USER
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_MANAGER_USER"
  - name: BB_KEYCLOAK_MANAGER_PASSWORD
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_MANAGER_PASSWORD"
  - name: BB_KEYCLOAK_CLIENTS_ADMIN
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENTS_ADMIN"
  - name: BB_KEYCLOAK_CLIENTS_BILLER
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENTS_BILLER"
  - name: BB_KEYCLOAK_CLIENTS_INTEGRATOR
    valueFrom: "{{ global_var_environment }}_{{ global_var_product }}_SECURE_BB_KEYCLOAK_CLIENTS_INTEGRATOR"

bb_securecorenginx_server_task_container_env:
  - name: FULL_GIT_URL
    value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/kb-nginx-configuration.git"
  - name: CONF_FILE
    value: "securecoreserver_uat.conf"
bb_securecore_server_task_container_env:
  - name: JAVA_OPTS
    value: "{{ bb_securecore_server_task_container_java_vars | join(' ') }}"    
  - name: BB_APP_DOWNLOAD_PATH
    value: "{{ bb_securecore_download_path }}"
  - name: BB_APP_IMAGE_PATH
    value: "{{ bb_securecore_image_path }}"
  - name: BB_APP_ELK_URL
    value: "https://{{ hostvars.localhost.reg_elasticsearch_cluster.Endpoints.vpc }}"
  - name: BB_APP_KAFKA_BOOSTRAP
    value: "{{ hostvars.localhost.reg_kafka_bootstrap_facts_ips_and_port }}"
  - name: BB_APP_CONTEXROOT
    value: "https://{{ global_var_services_details.securecoreserver.domain }}"
  - name: BB_APP_IMAGEROOT
    value: "{{ global_var_cloudfront_base_url }}"
  - name: FULL_GIT_URL
    value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/uat-kb-groovy-features.git"
  - name: BB_APP_S3_BUCKET
    value: "public.uat.usebillbox.com"
  - name: BB_APP_S3_ENDPOINTURL
    value: "https://s3-{{ global_var_ecs_region }}.amazonaws.com"
  - name: BB_APP_DATA_SHARE
    value: "/opt/repo"
  - name: BB_APP_S3_CDN
    value: "True"
  - name: BB_OWASP_RESC
    value: "{{bb_securecore_server_owasp_resc}}"
  - name: BB_MAX_LOGIN_ATTEMPT
    value: "{{bb_securecore_server_max_login_attempt}}"
  - name: BB_AUTH_CACHE_TTL
    value: "{{bb_securecore_server_auth_cache_ttl_mins}}"
  - name: BB_SETTLEMENT_WEEKEND_ENABLE
    value: "True"
  - name: BB_SESSION_TIMEOUT
    value: "15"
  - name: BB_KEYCLOAK_HOME
    value: "https://{{ global_var_services_details.keycloakserver.domain }}"
  - name: BB_KEYCLOAK_AUTH_URL
    value: "https://{{ global_var_services_details.keycloakserver.domain }}/auth"
  - name: BB_KEYCLOAK_CLIENT_PUBLIC
    value: "false"
  - name: BB_KEYCLOAK_ENABLE_BASIC_AUTH
    value: "true"
  - name: BB_APP_PROXY_NAME
    value: "{{ global_var_services_details.securecoreserver.domain }}"
  # - name: BB_APP_PROXY_PORT
  #   value: "{{ bb_securecore_network_lb_port }}"
  - name: "BB_KEYCLOAK_PRINCIPAL_ATTRIBUTE"
    value: "preferred_username"
  - name: BB_USE_FORWARD_HEADERS
    value: "{{ bb_securecore_server_max_use_forward_headers }}"
  - name: BB_REMOTE_IP_HEADER
    value: "X-FORWARDED-FOR"
  - name: BB_PROTOCOL_HEADER
    value: "X-FORWARDED-PROTO"
bb_securecore_server_task_container_mon_env_docker_env_tags:
  ENVIRONMENT: "{{ global_var_environment }}"    
bb_securecore_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    # value: '{{ { "ENVIRONMENT": global_var_environment } | to_json }}'
    value: "{{ bb_securecore_server_task_container_mon_env_docker_env_tags | to_json }}"
  - name: "DD_APM_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  - name: "DD_APM_ENABLED"
    value: "true" 
  - name: "DD_PROCESS_AGENT_ENABLED"
    value: "true" 
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  - name: "DD_APM_RECEIVER_PORT"
    value: "8126"
  - name: "DD_ENV"
    value: "{{ global_var_environment }}"
  - name: "DD_SERVICE"
    value: "{{ bb_securecore_service_name }}"
  - name: "DD_VERSION"
    value: "{{ global_var_services_details.securecoreserver.image.split(':')[1] }}"
bb_securecore_server_task_container_log_env:
  - name: "DD_ENV"
    value: "{{ global_var_environment }}"
  - name: "DD_SERVICE"
    value: "{{ bb_securecore_service_name }}"
  - name: "DD_VERSION"
    value: "{{ global_var_services_details.securecoreserver.image.split(':')[1] }}"
bb_securecore_server_task_container_mon_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
bb_securecore_server_task_container_log_driver: awslogs
bb_securecore_server_task_container_log_logsgroup: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-ecsgroup"
bb_securecore_server_task_container_log_logsregion: "{{ global_var_ird_region }}"
bb_securecore_server_task_container_log_logsprefix: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-"
bb_securecore_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
bb_securecore_service_name: "{{global_var_country_code}}-{{global_var_product}}-{{global_var_environment}}-{{ global_var_services_details.securecoreserver.name }}-service"
bb_securecore_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.securecoreserver.application_name }}TG"
bb_securecore_http_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-seccoreHTTPTG"
bb_securecore_targetgroup_protocol: "TCP"
bb_securecore_targetgroup_port: "443"
bb_securecore_http_targetgroup_port: "80"
# bb_securecore_ssl_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.securecoreserver.application_name }}SSLTG"
# bb_securecore_ssl_targetgroup_protocol: "https"
bb_securecore_targetgroup_success_http_code: 200
bb_securecore_targetgroup_hc_interval: 10
bb_securecore_targetgroup_hc_timeout: 5
bb_securecore_targetgroup_hc_healthycount: 3
bb_securecore_targetgroup_hc_unhealthycount: 3
bb_securecore_targetgroup_hc_path: "/login"
bb_securecore_targetgroup_hc_protocol: "tcp"
bb_securecore_targetgroup_hc_port: "{{ global_var_services_details.securecoreserver.containerPort }}"
# bb_securecore_ssl_targetgroup_hc_protocol: "https"
bb_securecore_targetgroup_targettype: "ip"

bb_securecore_service_count: 1
bb_securecore_service_platform_version: 1.3.0
bb_securecore_service_hc_graceperiod: 600
bb_securecore_service_autoscalling_policy_type: "TargetTrackingScaling"
bb_securecore_service_autoscalling_min_task: "{{ bb_securecore_service_count }}"
bb_securecore_service_autoscalling_max_task: 12
bb_securecore_service_mem_autoscalling_policy_name: "{{ bb_securecore_server_task_family_name }}-mem-as-policy"
bb_securecore_service_cpu_autoscalling_policy_name: "{{ bb_securecore_server_task_family_name }}-cpu-as-policy"
bb_securecore_service_mem_autoscalling_tracking_scaling_target_value: 70
bb_securecore_service_cpu_autoscalling_tracking_scaling_target_value: 50
bb_securecore_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
bb_securecore_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
bb_securecore_service_mem_autoscalling_tracking_scalout_cooldown: 60
bb_securecore_service_mem_autoscalling_tracking_scalin_cooldown: 60
bb_securecore_service_cpu_autoscalling_tracking_scalout_cooldown: 120
bb_securecore_service_cpu_autoscalling_tracking_scalin_cooldown: 180
bb_securecore_service_awscli_enabled: false
# bb_securecore_service_scheduled_autoscalling: true
# bb_securecore_service_wake_cron: "00 06 ? * MON-FRI *"
# bb_securecore_service_sleep_cron: "59 20 ? * MON-FRI *"

bb_securecore_proxyserver_name: securecoreproxy
bb_securecore_proxyserver_port: "443"
bb_securecore_network_lb_port: "443"

bb_securecore_proxyserver_task_container_env:
  - name: NGINX_LISTEN_PORT
    value: "{{ bb_securecore_proxyserver_port }}"
  - name: NGINX_SERVER_HOSTNAME
    value: "{{ global_var_services_details.securecoreserver.domain }}"
  - name: TEMPLATE_CONF_FILE
    value: "corebb_client_ssl.conf.template"
  - name: NGINX_PROXY_PORT
    value: "{{ global_var_services_details.securecoreserver.containerPort }}"
  - name: NGINX_PROXY_PASS
    value: "localhost:{{ global_var_services_details.securecoreserver.containerPort }}"
  - name: NGINX_ALLOW_SUBNET
    value: "{{ global_var_ird_vpc_cidr }}"
  - name: NGINX_SSL_CERT_FILE
    value: "star_doersops_com_bundle.crt"
  - name: NGINX_SSL_KEY_FILE
    value: "star_doersops_com.key"
  - name: NGINX_SSL_CA_FILE
    value: "{{ global_var_environment }}_BillboxROOTCA.crt"