
bb_bulkprocessor_main_port: 9595
bb_bulkprocessor_int_port: 9191
bb_bulkprocessor_tomcat_jmx_port: 13000
bb_bulkprocessor_server_enabled: true
bb_ctive_region: "{{ global_var_ird_region }}"
bb_ctive_priv_dns_namespace: "{{ global_var_priv_dns_namespace }}"
bb_bulkprocessor_server_task_family_name: "{{ global_var_country_code }}-{{ global_var_product }}-{{global_var_environment}}-{{ global_var_services_details.bulkprocessorserver.name }}"
bb_bulkprocessor_server_task_networkmode: awsvpc
bb_bulkprocessor_server_task_executionRoleArn: "{{ hostvars.localhost.reg_ecs_role_facts.iam_roles.0.arn }}"
bb_bulkprocessor_server_task_ecsmode: FARGATE
bb_bulkprocessor_server_task_cpu: 1024
bb_bulkprocessor_server_task_memory: 3072
bb_bulkprocessor_server_task_container_name: "{{ global_var_services_details.bulkprocessorserver.name }}"
bb_bulkprocessor_server_task_container_image: "{{ global_var_services_details.bulkprocessorserver.image }}"
bb_bulkprocessor_server_task_container_cpu: 1024
bb_bulkprocessor_server_task_container_memory: 3072
bb_bulkprocessor_server_task_container_memoryReservation: 1024
# bb_bulkprocessor_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_quayio_secrets_facts.ARN }}"
bb_bulkprocessor_server_task_container_credentials_parameter: "{{ hostvars.localhost.reg_dockerhub_secrets_facts.ARN }}"
bb_bulkprocessor_server_task_container_portmap_containerport: 8080
bb_bulkprocessor_server_task_container_portmap_hostport: 8080
bb_bulkprocessor_server_task_container_essential: true
bb_bulkprocessor_sidecar_server_task_container_essential: true
bb_bulkprocessor_image_path: "{{ global_var_cloudfront_base_url }}/static/images/"
bb_bulkprocessor_download_path: "{{ global_var_cloudfront_base_url }}/download/"
bb_bulkprocessor_server_owasp_resc: classpath:*.properties
bb_bulkprocessor_server_auth_cache_ttl_mins: "10"
bb_bulkprocessor_server_max_login_attempt: "3"
bb_bulkprocessor_server_max_use_forward_headers: "false"
bb_bulkprocessor_server_upload_folder: "file-uploads"
bb_bulkprocessor_server_processor_url: "https://kbcore.mykowri.com"
bb_bulkprocessor_server_maximum_upload_size: "10MB"
bb_bulkprocessor_server_s3_profile: "billbox"
bb_bulkprocessor_server_s3_bucket: "public.uat.usebillbox.com"
bb_bulkprocessor_server_s3_endpoint_url: "https://s3-{{ global_var_ecs_region }}.amazonaws.com"
bb_bulkprocessor_server_s3_cors_origin_allow: "http://localhost:3000"
bb_bulkprocessor_server_keycloak_auth_url: "https://kbauth.mykowri.com/auth/"
bb_bulkprocessor_server_keycloak_realm: "Billbox"
bb_bulkprocessor_server_keycloak_client_public: "false"
bb_bulkprocessor_server_keycloak_client_id: "billbox-bulk"
bb_bulkprocessor_server_keycloak_client_secret: "a59uL8UFDrFAqQtQPbwh0pKguZTebcAr"
bb_bulkprocessor_server_keycloak_principal_attribute: "preferred_username"
bb_bulkprocessor_server_keycloak_enable_basic_auth: "false"
bb_bulkprocessor_server_app_name: "bulk-processor"
bb_bulkprocessor_server_config_name: "bulk-processor"
bb_bulkprocessor_server_kafka_enable: "true"
bb_bulkprocessor_server_config_uri: "http://{{ global_var_services_details.configserver.name }}.{{ global_var_priv_dns_namespace }}:{{ global_var_services_details.configserver.hostPort }}"
bb_bulkprocessor_server_config_profiles: "dev,dev-mongo"
bb_bulkprocessor_server_health_detailed: "never"
bb_bulkprocessor_server_actuator_enable_all: "false"
bb_bulkprocessor_server_actuator_enable: "true"
bb_bulkprocessor_server_env_enable: "false"
bb_bulkprocessor_server_task_container_java_vars:
  - "-Xmx{{ bb_bulkprocessor_server_task_container_memory }}M"
  - "-XX:PermSize=256m -XX:MaxPermSize={{ bb_bulkprocessor_server_task_container_memoryReservation }}M"
  - "-XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled"
  - "-XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70"
  - "-XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark"
  - "-XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M"
  - "-Dsun.net.inetaddr.ttl=300"
  - "-Djava.rmi.server.hostname=localhost"
  - "-Dcom.sun.management.jmxremote"
  - "-Dcom.sun.management.jmxremote.port={{ bb_bulkprocessor_tomcat_jmx_port }}"
  - "-Dcom.sun.management.jmxremote.ssl=False"
  - "-Dcom.sun.management.jmxremote.authenticate=False"
  - "-Dhttps.protocols=TLSv1.2,TLSv1.1"
  - "-Djdk.tls.client.protocols=TLSv1.2,TLSv1.1"
  # - "-DLOGENTRIES_TOKEN={{ global_var_services_details.bulkprocessorserver.logToken }}"
  - "-Dauth.attempt.cache.duration.mins=10"
  - "-Dserver.use-forward-headers=false"
  - "-Ddd.agent.host=localhost"
  - "-Ddd.agent.port=8126"
  - "-Ddd.logs.injection=true"
  - "-Ddd.service={{ bb_bulkprocessor_service_name }}"
  - "-Ddd.env={{ global_var_environment }}"
  - "-Ddd.version={{ global_var_services_details.bulkprocessorserver.image.split(':')[1] }}"
  # - "-javaagent:/opt/datadog/dd-java-agent.jar"
bb_bulkprocessor_server_task_container_secretenv_definition:
  mongodb_uri:
    id: "{{ global_var_environment }}_BB_MONGO_URI"
    name: BB_MONGO_URI
    content: "mongodb://{{ vault_mongo_core_username }}:{{ vault_mongo_core_password }}@{{ hostvars.localhost.reg_mongo_cluster_uri }}/{{ vault_mongo_core_dbname }}?replicaSet={{ global_var_replicatset_name }}&readPreference=secondaryPreferred"
  mongodbname:
    id: "{{ global_var_environment }}_BB_MONGO_DBNAME"
    name: BB_MONGO_DBNAME
    content: "{{ vault_mongo_core_dbname }}"
  redishost:
    id: "{{ global_var_environment }}_BB_REDIS_HOST"
    name: BB_REDIS_HOST
    content: "{{ hostvars.localhost.reg_elasticache_facts }}"
  redisport:
    id: "{{ global_var_environment }}_BB_REDIS_PORT"
    name: BB_REDIS_PORT
    content: "{{ global_var_redis_port }}"
  s3profile:
    id: "{{ global_var_environment }}_BB_APP_S3_PROFILE"
    name: BB_APP_S3_PROFILE
    content: "{{ bb_bulkprocessor_server_s3_profile }}"
  keycloakauthurl:
    id: "{{ global_var_environment }}_BB_KEYCLOAK_AUTH_URL"
    name: BB_KEYCLOAK_AUTH_URL
    content: "{{ bb_bulkprocessor_server_keycloak_auth_url }}"
  keycloakrealm:
    id: "{{ global_var_environment }}_BB_KEYCLOAK_REALM"
    name: BB_KEYCLOAK_REALM
    content: "{{ bb_bulkprocessor_server_keycloak_realm }}"
  keycloak_clientid:
    id: "{{ global_var_environment }}_BB_KEYCLOAK_CLIENT_ID"
    name: BB_KEYCLOAK_CLIENT_ID
    content: "{{ bb_bulkprocessor_server_keycloak_client_id }}"
  keycloak_client_secret:
    id: "{{ global_var_environment }}_BB_KEYCLOAK_CLIENT_SECRET"
    name: BB_KEYCLOAK_CLIENT_SECRET
    content: "{{ bb_bulkprocessor_server_keycloak_client_secret }}"
  keycloak_principal_attb:
    id: "{{ global_var_environment }}_BB_KEYCLOAK_PRINCIPAL_ATTRIBUTE"
    name: BB_KEYCLOAK_PRINCIPAL_ATTRIBUTE
    content: "{{ bb_bulkprocessor_server_keycloak_principal_attribute }}"



bb_bulkprocessor_server_task_container_secretenv:
  - valueFrom: "{{ global_var_environment }}_BB_KEYCLOAK_REALM"
    name: BB_KEYCLOAK_REALM
  - valueFrom: "{{ global_var_environment }}_BB_KEYCLOAK_AUTH_URL"
    name: BB_KEYCLOAK_AUTH_URL
  - valueFrom: "{{ global_var_environment }}_BB_APP_S3_PROFILE"
    name: BB_APP_S3_PROFILE
  - valueFrom: "{{ global_var_environment }}_BB_REDIS_PORT"
    name: BB_REDIS_PORT
  - valueFrom: "{{ global_var_environment }}_BB_REDIS_HOST"
    name: BB_REDIS_HOST
  - valueFrom: "{{ global_var_environment }}_BB_MONGO_URI"
    name: BB_MONGO_URI
  - valueFrom: "{{ global_var_environment }}_BB_MONGO_DBNAME"
    name: BB_MONGO_DBNAME
  - valueFrom: "{{ global_var_environment }}_BB_KEYCLOAK_CLIENT_ID"
    name: BB_KEYCLOAK_CLIENT_ID
  - valueFrom: "{{ global_var_environment }}_BB_KEYCLOAK_CLIENT_SECRET"
    name: BB_KEYCLOAK_CLIENT_SECRET
  - valueFrom: "{{ global_var_environment }}_BB_KEYCLOAK_PRINCIPAL_ATTRIBUTE"
    name: BB_KEYCLOAK_PRINCIPAL_ATTRIBUTE


bb_bulkprocessornginx_server_task_container_env:
  # - name: FULL_GIT_URL
  #   value: "https://{{ vault_git_username }}:{{ vault_git_token }}@bitbucket.org/kowri/kb-nginx-configuration.git"
  # - name: CONF_FILE
  #   value: "coreserver_uat.conf"
  - name: NGINX_LISTEN_PORT
    value: "{{ bb_bulkprocessor_proxyserver_listen_port }}"
  - name: NGINX_SERVER_HOSTNAME
    value: "{{ bb_bulkprocessor_proxyserver_domain_name }}"
  - name: TEMPLATE_CONF_FILE
    value: "{{ bb_bulkprocessor_proxyserver_template_name }}"
  - name: NGINX_PROXY_PASS
    value: "localhost:{{ bb_bulkprocessor_proxyserver_proxypass_port }}"
  - name: NGINX_ALLOW_SUBNET
    value: "{{ global_var_ird_vpc_cidr }}"  
  - name: NGINX_HEADER_CSP
    value: "{{ bb_bulkprocessor_proxyserver_csp_values }}"  
bb_bulkprocessor_server_task_container_env:
  - name: BB_BULK_PROCESSOR_UPLOAD_FOLDER
    value: "{{ bb_bulkprocessor_server_upload_folder }}"
  - name: BB_BULK_PROCESSOR_PROCESSOR_URL
    value: "{{ bb_bulkprocessor_server_processor_url }}"
  - name: BB_BULK_PROCESSOR_UPLOAD_SIZE_MAX
    value: "{{ bb_bulkprocessor_server_maximum_upload_size }}"
  - name: BB_APP_S3_BUCKET
    value: "{{ bb_bulkprocessor_server_s3_bucket }}"
  - name: BB_APP_S3_ENDPOINTURL
    value: "{{ bb_bulkprocessor_server_s3_endpoint_url }}"
  - name: BB_BULK_CORS_ALLOW
    value: "{{ bb_bulkprocessor_server_s3_cors_origin_allow }}"
  - name: BB_KEYCLOAK_CLIENT_PUBLIC
    value: "{{ bb_bulkprocessor_server_keycloak_client_public }}"
  - name: BB_KEYCLOAK_ENABLE_BASIC_AUTH
    value: "{{ bb_bulkprocessor_server_keycloak_enable_basic_auth }}"
  - name: JAVA_OPTS
    value: "{{ bb_bulkprocessor_server_task_container_java_vars | join(' ') }}"
  - name: BB_BULK_PROCESSOR_APP_NAME
    value: "{{ bb_bulkprocessor_server_app_name }}"
  - name: BB_BULK_PROCESSOR_CONFIG_NAME
    value: "{{ bb_bulkprocessor_server_config_name }}"
  - name: BB_BULK_PROCESSOR_CONFIG_URI
    value: "{{ bb_bulkprocessor_server_config_uri }}"
  - name: BB_BULK_PROCESSOR_CONFIG_PROFILES
    value: "{{ bb_bulkprocessor_server_config_profiles }}"
  - name: BB_BULK_PROCESSOR_HEALTH_DETAILED
    value: "{{ bb_bulkprocessor_server_health_detailed }}"
  - name: BB_BULK_PROCESSOR_ACTUATOR_ENABLEALL
    value: "{{ bb_bulkprocessor_server_actuator_enable_all }}"
  - name: BB_BULK_PROCESSOR_HEALTH_ENABLE
    value: "{{ bb_bulkprocessor_server_actuator_enable }}"
  - name: BB_BULK_PROCESSOR_ENV_ENABLE
    value: "{{ bb_bulkprocessor_server_env_enable }}"
  # - name: BB_APP_S3_ENDPOINTURL
  #   value: "https://s3-{{ global_var_ecs_region }}.amazonaws.com"
  # - name: BB_APP_DATA_SHARE
  #   value: "/opt/repo"
  # - name: BB_APP_S3_CDN
  #   value: "True"
  # - name: BB_OWASP_RESC
  #   value: "{{bb_bulkprocessor_server_owasp_resc}}"
  # - name: BB_MAX_LOGIN_ATTEMPT
  #   value: "{{bb_bulkprocessor_server_max_login_attempt}}"
  # - name: BB_AUTH_CACHE_TTL
  #   value: "{{bb_bulkprocessor_server_auth_cache_ttl_mins}}"
  # - name: BB_USE_FORWARD_HEADERS
  #   value: "{{ bb_bulkprocessor_server_max_use_forward_headers }}"
  # - name: BB_SETTLEMENT_WEEKEND_ENABLE
  #   value: "True"
  # - name: BB_SESSION_TIMEOUT
  #   value: "15"
  # - name: BB_CORS_ORIGIN_ALLOW
  #   value: "localhost:11000"
  # - name: BB_KAFKA_ENABLE
  #   value: "{{ bb_bulkprocessor_server_kafka_enable }}"
bb_bulkprocessor_server_task_container_mon_env_docker_env_tags:
  ENVIRONMENT: "{{ global_var_environment }}"
bb_bulkprocessor_server_task_container_mon_env:
  - name: "DD_DOCKER_ENV_AS_TAGS"
    # value: '{{ { "ENVIRONMENT": global_var_environment } | to_json }}'
    value: "{{ bb_bulkprocessor_server_task_container_mon_env_docker_env_tags | to_json }}"
  - name: "DD_APM_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "ECS_FARGATE"
    value: "true"
  - name: "DD_APM_ENABLED"
    value: "true"
  - name: "DD_PROCESS_AGENT_ENABLED"
    value: "true"
  - name: "DD_DOGSTATSD_NON_LOCAL_TRAFFIC"
    value: "true"
  - name: "DD_DOGSTATSD_PORT"
    value: "8125"
  - name: "DD_APM_RECEIVER_PORT"
    value: "8126"
  - name: "DD_ENV"
    value: "{{ global_var_environment }}"
  - name: "DD_SERVICE"
    value: "{{ bb_bulkprocessor_service_name }}"
  - name: "DD_VERSION"
    value: "{{ global_var_services_details.bulkprocessorserver.image.split(':')[1] }}"
bb_bulkprocessor_server_task_container_log_env:
  - name: "DD_ENV"
    value: "{{ global_var_environment }}"
  - name: "DD_SERVICE"
    value: "{{ bb_bulkprocessor_service_name }}"
  - name: "DD_VERSION"
    value: "{{ global_var_services_details.bulkprocessorserver.image.split(':')[1] }}"
bb_bulkprocessor_server_task_container_mon_secretenv:
  - valueFrom: "{{ global_var_environment }}_DD_API_KEY"
    name: DD_API_KEY
bb_bulkprocessor_server_task_container_log_driver: awslogs
bb_bulkprocessor_server_task_container_log_logsgroup: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-ecsgroup"
bb_bulkprocessor_server_task_container_log_logsregion: "{{ global_var_ird_region }}"
bb_bulkprocessor_server_task_container_log_logsprefix: "{{ global_var_country_code }}-{{ global_var_product }}-{{ global_var_environment }}-"
bb_bulkprocessor_alb_arn: "{{ hostvars.localhost.reg_alb_facts.load_balancers.0.load_balancer_arn }}"
bb_bulkprocessor_service_name: "{{global_var_country_code}}-{{global_var_product}}-{{global_var_environment}}-{{ global_var_services_details.bulkprocessorserver.name }}-service"
bb_bulkprocessor_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.bulkprocessorserver.application_name }}TG"
bb_bulkprocessor_targetgroup_protocol: "http"
# bb_bulkprocessor_ssl_targetgroup_name: "{{ global_var_product }}-{{ global_var_environment }}-{{ global_var_services_details.bulkprocessor_server.application_name }}SSLTG"
# bb_bulkprocessor_ssl_targetgroup_protocol: "https"
bb_bulkprocessor_targetgroup_success_http_code: 200
bb_bulkprocessor_targetgroup_hc_interval: 6
bb_bulkprocessor_targetgroup_hc_timeout: 5
bb_bulkprocessor_targetgroup_hc_healthycount: 3
bb_bulkprocessor_targetgroup_hc_unhealthycount: 3
bb_bulkprocessor_targetgroup_hc_path: "/health"
bb_bulkprocessor_targetgroup_hc_protocol: "http"
# bb_bulkprocessor_ssl_targetgroup_hc_protocol: "https"
bb_bulkprocessor_targetgroup_targettype: "ip"

bb_bulkprocessor_service_count: 1
bb_bulkprocessor_service_platform_version: 1.3.0
bb_bulkprocessor_service_hc_graceperiod: 600
bb_bulkprocessor_service_autoscalling_policy_type: "TargetTrackingScaling"
bb_bulkprocessor_service_autoscalling_min_task: "{{ bb_bulkprocessor_service_count }}"
bb_bulkprocessor_service_autoscalling_max_task: 12
bb_bulkprocessor_service_mem_autoscalling_policy_name: "{{ bb_bulkprocessor_server_task_family_name }}-mem-as-policy"
bb_bulkprocessor_service_cpu_autoscalling_policy_name: "{{ bb_bulkprocessor_server_task_family_name }}-cpu-as-policy"
bb_bulkprocessor_service_mem_autoscalling_tracking_scaling_target_value: 70
bb_bulkprocessor_service_cpu_autoscalling_tracking_scaling_target_value: 50
bb_bulkprocessor_service_mem_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageMemoryUtilization"
bb_bulkprocessor_service_cpu_autoscalling_tracking_scaling_metric_spec: "ECSServiceAverageCPUUtilization"
bb_bulkprocessor_service_mem_autoscalling_tracking_scalout_cooldown: 60
bb_bulkprocessor_service_mem_autoscalling_tracking_scalin_cooldown: 60
bb_bulkprocessor_service_cpu_autoscalling_tracking_scalout_cooldown: 120
bb_bulkprocessor_service_cpu_autoscalling_tracking_scalin_cooldown: 180
bb_bulkprocessor_service_awscli_enabled: false
# bb_bulkprocessor_service_scheduled_autoscalling: true
# bb_bulkprocessor_service_wake_cron: "00 06 ? * MON-FRI *"
# bb_bulkprocessor_service_sleep_cron: "59 20 ? * MON-FRI *"
bb_bulkprocessor_proxyserver_listen_port: "80"
bb_bulkprocessor_proxyserver_name: bulkprocessorproxy
bb_bulkprocessor_proxyserver_domain_name: "{{ global_var_services_details.bulkprocessorserver.domain }}"
bb_bulkprocessor_proxyserver_template_name: "kb_core.conf.template"
bb_bulkprocessor_proxyserver_proxypass_port: "{{ global_var_services_details.bulkprocessorserver.containerPort }}"
bb_bulkprocessor_proxyserver_csp_values: "frame-ancestors 'none'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://ajax.googleapis.com https://fonts.googleapis.com https://www.gstatic.com https://www.google-analytics.com https://www.googletagmanager.com; font-src 'self' https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' https://www.google.com https://www.google.com.gh"
bb_bulkprocessor_service_monitoringserver_image: "datadog/agent:latest"
bb_bulkprocessor_service_monitoringserver_name: "datadog-agent"