---
proxy_ghairtigobankint_vhost_file: "forward_gh_airtigo_bank_int.conf"
ghairtigobankint_upstream_host1: "172.26.98.75:8585"
ghairtigobankint_upstream_host1_mon_type: tcp
ghairtigobankint_upstream_host1_mon_scheme: https
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_ghairtigobankint:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_ghairtigobankint_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_ghairtigobankint_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "/var/log/nginx/forward_ghairtigobankint_nginx_proxy_access.log"
    access_format: "jsonlog"
    error_log_file: "/var/log/nginx/forward_ghairtigobankint_nginx_proxy_error.log"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ ghairtigobankint_upstream_host1_mon_scheme }}://{{ ghairtigobankint_upstream_host1 }}/"
webserverfamily_nginx_deletefiles_details:
  - "/etc/nginx/sites-enabled/default"
webserverfamily_nginx_common_enable_sites_details_hash:
  ghairtigobankint:
    vhost: "{{ proxy_ghairtigobankint_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  ghairtigobankint:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/ghairtigobankint.yml"
      type: "{{ ghairtigobankint_upstream_host1_mon_type }}"
      name: "ghairtigobankint"
      enabled: true
      schedule: "@every 30s"
      hosts: ["{{ghairtigobankint_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"