---
proxy_ghgwcl_vhost_file: "forward_gh_gwcl.conf"
ghgwcl_upstream_host1: "10.0.0.4:7451"
ghgwcl_upstream_host1_mon_type: tcp
ghgwcl_upstream_host1_mon_scheme: https
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_ghgwcl:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_ghgwcl_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_ghgwcl_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "/var/log/nginx/forward_ghgwcl_nginx_proxy_access.log"
    access_format: "jsonlog"
    error_log_file: "/var/log/nginx/forward_ghgwcl_nginx_proxy_error.log"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ ghgwcl_upstream_host1_mon_scheme }}://{{ ghgwcl_upstream_host1 }}/"
webserverfamily_nginx_deletefiles_details:
  - "/etc/nginx/sites-enabled/default"
webserverfamily_nginx_common_enable_sites_details_hash:
  ghgwcl:
    vhost: "{{ proxy_ghgwcl_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  ghgwcl:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/ghgwcl.yml"
      type: "{{ ghgwcl_upstream_host1_mon_type }}"
      name: "ghgwcl"
      enabled: true
      schedule: "@every 30s"
      hosts: ["{{ghgwcl_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"