---
proxy_ghria_vhost_file: "forward_ghria.conf"
ghria_upstream_host1: "fxglobalwebsvcssl.riaenvia.net:9772"
ghria_upstream_host1_mon_type: tcp
ghria_upstream_host1_mon_scheme: https
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_ghria:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_ghria_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_ghria_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "/var/log/nginx/forward_ghria_nginx_proxy_access.log"
    access_format: "jsonlog"
    error_log_file: "/var/log/nginx/forward_ghria_nginx_proxy_error.log"
    bodyinstructions:
      - >
        proxy_ssl_certificate
        {{ global_var_billbox_ssl_folder_path }}/{{ global_var_billbox_ssl_cert }}
      - >
        proxy_ssl_certificate_key
        {{ global_var_billbox_ssl_folder_path }}/{{ global_var_billbox_ssl_key }}
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for"
          - "proxy_pass {{ ghria_upstream_host1_mon_scheme }}://{{ ghria_upstream_host1 }}/"
webserverfamily_nginx_deletefiles_details:
  - "/etc/nginx/sites-enabled/default"
webserverfamily_nginx_common_enable_sites_details_hash:
  ghria:
    vhost: "{{ proxy_ghria_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  ghria:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/ghria.yml"
      type: "{{ ghria_upstream_host1_mon_type }}"
      name: "ghria"
      enabled: true
      schedule: "@every 30s"
      hosts: ["{{ghria_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"