---
local_vars_proxy_forward_gh_niacard_vhost_file: "forward_gh_niacard.conf"
local_vars_proxy_forward_gh_niacard_log_access_file: "/var/log/nginx/forward_gh_niacard_nginx_proxy_access.log"
local_vars_proxy_forward_gh_niacard_log_error_file: "/var/log/nginx/forward_gh_niacard_nginx_proxy_error.log"
forward_gh_niacard_upstream_1_host: "selfie.imsgh.org:9020"
# forward_gh_niacard_upstream_1_host_mon_host1: "payonline.econet.co.zw/ecocashGateway/payment/v1/transactions/amount"
forward_gh_niacard_upstream_1_host_mon_type: tcp
forward_gh_niacard_upstream_1_host_mon_scheme: https
webserverfamily_nginx_enable: true
webserverfamily_nginx_push_configfiles_details:
  forward_gh_niacard:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ local_vars_proxy_forward_gh_niacard_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_forward_gh_niacard_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ local_vars_proxy_forward_gh_niacard_log_access_file }}"
    access_format: "jsonlog"
    error_log_file: "{{ local_vars_proxy_forward_gh_niacard_log_error_file }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ forward_gh_niacard_upstream_1_host_mon_scheme}}://{{ forward_gh_niacard_upstream_1_host }}/"
webserverfamily_nginx_common_enable_sites_details_hash:
  forward_gh_niacard:
    vhost: "{{ local_vars_proxy_forward_gh_niacard_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  forward_gh_niacard:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/forward_gh_niacard.yml"
      type: "{{ forward_gh_niacard_upstream_1_host_mon_type }}"
      name: "forward_gh_niacard"
      enabled: true
      schedule: "@every 1h"
      hosts: ["{{ forward_gh_niacard_upstream_1_host }}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['tags']['AName'] }}"
monitoringfamily_enable_r7insightops: true
monitoringfamily_r7insightops_config_path: "/opt/rapid7/ir_agent/components/insight_agent/common/config"
monitoringfamily_r7insightops_forward_gh_niacard_accesslog_name: "NginxProxy_Forward_GH_NIACard_Access_log"
monitoringfamily_r7insightops_forward_gh_niacard_errorlog_name: "NginxProxy_Forward_GH_NIACard_Error_log"
monitoringfamily_r7insightops_agent_block_templating_details:
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  path: "/config/logs"
  # src: "rapid7_insightops/config_block.j2"
  type: "inject"
  blocks:
    - {
        destination: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_niacard_accesslog_name }}",
        enabled: "true",
        name: "{{ monitoringfamily_r7insightops_forward_gh_niacard_accesslog_name }}",
        path: "{{ local_vars_proxy_forward_gh_niacard_log_access_file }}"
    }
    - {
        destination: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_niacard_errorlog_name }}",
        enabled: "true",
        name: "{{ monitoringfamily_r7insightops_forward_gh_niacard_errorlog_name }}",
        path: "{{ local_vars_proxy_forward_gh_niacard_log_error_file }}"
    }
monitoringfamily_r7insightops_agent_overwrite_config_details:
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  src: "rapid7_insightops/empty_config.j2"
monitoringfamily_r7insightops_enable_file_rewrite: false  
monitoringfamily_r7insightops_agent_restart_enabled: true
forward_gh_niacard_targetgroup_name: fwd-gh-niacardTG
forward_gh_niacard_targetgroup_protocol: "http"
forward_gh_niacard_targetgroup_success_http_code: 200
forward_gh_niacard_targetgroup_hc_interval: 6
forward_gh_niacard_targetgroup_hc_timeout: 5
forward_gh_niacard_targetgroup_hc_healthycount: 3
forward_gh_niacard_targetgroup_hc_unhealthycount: 3
forward_gh_niacard_targetgroup_hc_path: "/test"
forward_gh_niacard_targetgroup_hc_protocol: "http"
forward_gh_niacard_targetgroup_targettype: "instance"