---
proxy_forward_gh_zeepaymomo_vhost_file: "forward_gh_zeepaymomo.conf"
proxy_forward_gh_zeepaymomo_log_access_file: "/var/log/nginx/forward_gh_zeepaymomo_nginx_proxy_access.log"
proxy_forward_gh_zeepaymomo_log_error_file: "/var/log/nginx/forward_gh_zeepaymomo_nginx_proxy_error.log"
proxy_forward_gh_zeepaymomo_upstream_host1: "m-money-sandbox.myzeepay.com:443"
proxy_forward_gh_zeepaymomo_upstream_host1_mon_type: tcp
proxy_forward_gh_zeepaymomo_upstream_host1_mon_scheme: https
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_gh_zeepaymomo:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_forward_gh_zeepaymomo_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_gh_zeepaymomo_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ proxy_forward_gh_zeepaymomo_log_access_file }}"
    access_format: "jsonlog"
    error_log_file: "{{ proxy_forward_gh_zeepaymomo_log_error_file }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ proxy_forward_gh_zeepaymomo_upstream_host1_mon_scheme }}://{{ proxy_forward_gh_zeepaymomo_upstream_host1 }}/"

webserverfamily_nginx_common_enable_sites_details_hash:
  forward_gh_zeepaymomo:
    vhost: "{{ proxy_forward_gh_zeepaymomo_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  forward_gh_zeepaymomo:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/gh_zeepaymomo.yml"
      type: "{{ proxy_forward_gh_zeepaymomo_upstream_host1_mon_type }}"
      name: "gh_zeepaymomo"
      enabled: true
      schedule: "@every 1h"
      hosts: ["{{proxy_forward_gh_zeepaymomo_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"
monitoringfamily_r7insightops_forward_gh_zeepaymomo_accesslog_name: "NginxProxy_Forward_GH_ZEEPAYmomo_Access_log"
monitoringfamily_r7insightops_forward_gh_zeepaymomo_errorlog_name: "NginxProxy_Forward_GH_ZEEPAYmomo_Error_log"
monitoringfamily_r7insightops_agent_templating_details:
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  src: "rapid7_insightops/config.j2"
  api_key: "{{ vault_rapid7insightops_apikey }}"
  servername: "{{ inventory_hostname }}"
monitoringfamily_r7insightops_agent_templating_data:
  forward_gh_zeepaymomo:
      appnginxaccess:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_zeepaymomo_accesslog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_zeepaymomo_accesslog_name }}"
        path: "{{ proxy_forward_gh_zeepaymomo_log_access_file }}"
      appnginxerror:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_zeepaymomo_errorlog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_zeepaymomo_errorlog_name }}"
        path: "{{ proxy_forward_gh_zeepaymomo_log_error_file }}"
      
proxy_forward_gh_zeepaymomoTG:
  name: "bb-{{ global_var_environment }}-fwd-gh-zeepaymomoTG"
  port: "{{ global_gh_zeepaymomo_nginx_port }}"
  priority: 30
  protocol: http
  success_response_code: 200
  check_interval: 5
  check_timeout: 3
  check_path: /test
  check_protocol: http
  healthy_count: 3
  unhealthy_count: 3
  target_type: instance
  targets: "{{ lookup('template','templates/elb_target_group_list.j2',template_vars=dict(bb_target_list=hostvars.localhost.reg_proxy_instance_ids,bb_target_port=global_gh_zeepaymomo_nginx_port)) | from_yaml }}"
  tags:
    Name: "bb-{{ global_var_environment }}-fwd-gh-zeepaymomoTG"
    ENV: "{{ global_var_environment }}"
    Product: Billbox
    ProxyDirection: Forward
    Partner: ZeePay
      

    

