---
proxy_forward_gh_appsnmobaiterltigo_vhost_file: "forward_gh_appsnmobaiterltigo.conf"
proxy_forward_gh_appsnmobaiterltigo_log_access_file: "/var/log/nginx/forward_gh_appsnmobaiterltigo_nginx_proxy_access.log"
proxy_forward_gh_appsnmobaiterltigo_log_error_file: "/var/log/nginx/forward_gh_appsnmobaiterltigo_nginx_proxy_error.log"
forward_gh_appsnmobaiterltigo_upstream_host1: "payalert-api.anmgw.com:443"
# forward_gh_appsnmobaiterltigo_upstream_host1_mon_host1: "payonline.econet.co.zw/ecocashGateway/payment/v1/transactions/amount"
forward_gh_appsnmobaiterltigo_upstream_host1_mon_type: tcp
forward_gh_appsnmobaiterltigo_upstream_host1_mon_scheme: https
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_gh_appsnmobaiterltigo:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_forward_gh_appsnmobaiterltigo_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_forward_gh_appsnmobaiterltigo_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ proxy_forward_gh_appsnmobaiterltigo_log_access_file }}"
    access_format: "jsonlog"
    error_log_file: "{{ proxy_forward_gh_appsnmobaiterltigo_log_error_file }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ forward_gh_appsnmobaiterltigo_upstream_host1_mon_scheme}}://{{ forward_gh_appsnmobaiterltigo_upstream_host1 }}/"

webserverfamily_nginx_common_enable_sites_details_hash:
  forward_gh_appsnmobaiterltigo:
    vhost: "{{ proxy_forward_gh_appsnmobaiterltigo_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  forward_gh_appsnmobaiterltigo:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/forward_gh_appsnmobaiterltigo.yml"
      type: "{{ forward_gh_appsnmobaiterltigo_upstream_host1_mon_type }}"
      name: "forward_gh_appsnmobaiterltigo"
      enabled: true
      schedule: "@every 1h"
      hosts: ["{{ forward_gh_appsnmobaiterltigo_upstream_host1 }}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"
monitoringfamily_r7insightops_forward_gh_appsnmobaiterltigo_accesslog_name: "NginxProxy_Forward_gh_AppsnMobAiterlTigo_Access_log"
monitoringfamily_r7insightops_forward_gh_appsnmobaiterltigo_errorlog_name: "NginxProxy_Forward_gh_AppsnMobAiterlTigo_Error_log"
monitoringfamily_r7insightops_agent_templating_details:
  api_key: "{{ vault_rapid7insightops_apikey }}"
  servername: "{{ inventory_hostname }}"
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  src: "rapid7_insightops/config.j2"
monitoringfamily_r7insightops_agent_templating_data:
  forward_gh_appsnmobaiterltigo:
      appnginxaccess:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_appsnmobaiterltigo_accesslog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_appsnmobaiterltigo_accesslog_name }}"
        path: "{{ proxy_forward_gh_appsnmobaiterltigo_log_access_file }}"
      appnginxerror:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_appsnmobaiterltigo_errorlog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_appsnmobaiterltigo_errorlog_name }}"
        path: "{{ proxy_forward_gh_appsnmobaiterltigo_log_error_file }}"