---
proxy_forward_gh_mtnairtime_vhost_file: "forward_gh_mtnairtime.conf"
proxy_forward_gh_mtnairtime_log_access_file: "/var/log/nginx/forward_gh_mtnairtime_nginx_proxy_access.log"
proxy_forward_gh_mtnairtime_log_error_file: "/var/log/nginx/forward_gh_mtnairtime_nginx_proxy_error.log"
proxy_forward_gh_mtnairtime_upstream_host1: 10.130.3.144:8913
proxy_forward_gh_mtnairtime_upstream_host1_mon_type: tcp
proxy_forward_gh_mtnairtime_upstream_host1_mon_scheme: https
proxy_forward_gh_mtnairtime_access_log: "/var/log/nginx/forward_gh_mtnairtime_nginx_proxy_access.log"
proxy_forward_gh_mtnairtime_error_log: "/var/log/nginx/forward_gh_mtnairtime_nginx_proxy_error.log"
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_gh_mtnairtime:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_forward_gh_mtnairtime_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_forward_gh_mtnairtime_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ proxy_forward_gh_mtnairtime_access_log }}"
    access_format: "jsonlog"
    error_log_file: "{{ proxy_forward_gh_mtnairtime_error_log }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ proxy_forward_gh_mtnairtime_upstream_host1_mon_scheme }}://{{ proxy_forward_gh_mtnairtime_upstream_host1 }}/"
webserverfamily_nginx_deletefiles_details:
  - "/etc/nginx/sites-enabled/default"
webserverfamily_nginx_common_enable_sites_details_hash:
  forward_gh_mtnairtime:
    vhost: "{{ proxy_forward_gh_mtnairtime_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  forward_gh_mtnairtime:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/forward_gh_mtnairtime.yml"
      type: "{{ proxy_forward_gh_mtnairtime_upstream_host1_mon_type }}"
      name: "forward_gh_mtnairtime"
      enabled: true
      schedule: "@every 1h"
      hosts: ["{{proxy_forward_gh_mtnairtime_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"
monitoringfamily_r7insightops_forward_gh_mtnairtime_accesslog_name: "NginxProxy_Forward_GH_MTNAirtime_Access_log"
monitoringfamily_r7insightops_forward_gh_mtnairtime_errorlog_name: "NginxProxy_Forward_GH_MTNAirtime_Error_log"
monitoringfamily_r7insightops_agent_templating_details:
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  src: "rapid7_insightops/config.j2"
  api_key: "{{ vault_rapid7insightops_apikey }}"
  servername: "{{ inventory_hostname }}"
monitoringfamily_r7insightops_agent_templating_data:
  forward_gh_mtnairtime:
      appnginxaccess:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_mtnairtime_accesslog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_mtnairtime_accesslog_name }}"
        path: "{{ proxy_forward_zw_econet_log_access_file }}"
      appnginxerror:
        r7dest: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_mtnairtime_errorlog_name }}"
        enabled: "true"
        name: "{{ monitoringfamily_r7insightops_forward_gh_mtnairtime_errorlog_name }}"
        path: "{{ proxy_forward_zw_econet_log_error_file }}"     