---
local_vars_proxy_forward_gh_ghipss_vhost_file: "forward_gh_ghipss.conf"
local_vars_proxy_forward_gh_ghipss_log_access_file: "/var/log/nginx/forward_gh_ghipss_nginx_proxy_access.log"
local_vars_proxy_forward_gh_ghipss_log_error_file: "/var/log/nginx/forward_gh_ghipss_nginx_proxy_error.log"
local_vars_proxy_forward_gh_ghipss_ssl_year: "2022_2023"
proxy_forward_gh_ghipss_upstream_host1: "ghqr-test.fin.ghipss.com:7543"
proxy_forward_gh_ghipss_upstream_host1_mon_type: tcp
proxy_forward_gh_ghipss_upstream_host1_mon_scheme: https
local_vars_proxy_forward_gh_ghipss_ssl_cert: "ghipss_clientssl_mykowri_com_bundle.crt"
local_vars_proxy_forward_gh_ghipss_ssl_key: "ghipss_clientssl_mykowri_com.key"
local_vars_proxy_forward_gh_ghipss_ssl_folder_path: "/srv/ssl/client/proxy_forward_gh_ghipss/{{ local_vars_proxy_forward_gh_ghipss_ssl_year }}"
util_filesystem_enable: true
util_filesystem_create_directory_with_pem_details_dict:
  proxy_forward_gh_ghipss:
    path: "{{ local_vars_proxy_forward_gh_ghipss_ssl_folder_path }}"
# aws_install_python_pip_enable: true
# aws_pip_install_boto_enable: true
aws_install_awscli_enable: true
aws_s3_enable: true
aws_s3_pull_object_details:
  forward_gh_ghipss_cert:
    bucket: "{{ global_var_billbox_s3_bucket }}"
    objpath: "{{ global_var_billbox_s3_client_ssl_bucket_key }}/forward_gh_ghipss/{{ local_vars_proxy_forward_gh_ghipss_ssl_year }}/{{ local_vars_proxy_forward_gh_ghipss_ssl_cert }}"
    dest_path: "{{ local_vars_proxy_forward_gh_ghipss_ssl_folder_path }}/{{ local_vars_proxy_forward_gh_ghipss_ssl_cert }}"
  forward_gh_ghipss_key:
    bucket: "{{ global_var_billbox_s3_bucket }}"
    objpath: "{{ global_var_billbox_s3_client_ssl_bucket_key }}/forward_gh_ghipss/{{ local_vars_proxy_forward_gh_ghipss_ssl_year }}/{{ local_vars_proxy_forward_gh_ghipss_ssl_key }}"
    dest_path: "{{ local_vars_proxy_forward_gh_ghipss_ssl_folder_path }}/{{ local_vars_proxy_forward_gh_ghipss_ssl_key }}"
webserverfamily_nginx_enable: true
webserverfamily_nginx_push_configfiles_details:
  forward_gh_ghipss:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ local_vars_proxy_forward_gh_ghipss_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_gh_ghipss_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "{{ local_vars_proxy_forward_gh_ghipss_log_access_file }}"
    access_format: "jsonlog"
    error_log_file: "{{ local_vars_proxy_forward_gh_ghipss_log_error_file }}"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ proxy_forward_gh_ghipss_upstream_host1_mon_scheme }}://{{ proxy_forward_gh_ghipss_upstream_host1 }}/"
webserverfamily_nginx_common_enable_sites_details_hash:
  forward_gh_ghipss:
    vhost: "{{ local_vars_proxy_forward_gh_ghipss_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  forward_gh_ghipss:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/gh_ghipss.yml"
      type: "{{ proxy_forward_gh_ghipss_upstream_host1_mon_type }}"
      name: "forward_gh_ghipss"
      enabled: true
      schedule: "@every 1h"
      hosts: ["{{proxy_forward_gh_ghipss_upstream_host1}}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['tags']['AName'] }}"
monitoringfamily_r7insightops_forward_gh_ghipss_accesslog_name: "NginxProxy_Forward_GH_Ghipss_Access_log"
monitoringfamily_r7insightops_forward_gh_ghipss_errorlog_name: "NginxProxy_Forward_GH_Ghipss_Error_log"
monitoringfamily_r7insightops_config_path: "/opt/rapid7/ir_agent/components/insight_agent/common/config"

monitoringfamily_enable_r7insightops: true
monitoringfamily_r7insightops_agent_block_templating_details:
  dest: "{{ monitoringfamily_r7insightops_config_path }}/logging.json"
  path: "/config/logs"
  # src: "rapid7_insightops/config_block.j2"
  type: "inject"
  blocks:
    - {
        destination: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_ghipss_accesslog_name }}",
        enabled: "true",
        name: "{{ monitoringfamily_r7insightops_forward_gh_ghipss_accesslog_name }}",
        path: "{{ local_vars_proxy_forward_gh_ghipss_log_access_file }}"
    }
    - {
        destination: "{{ global_var_insightops_log_set }}/{{ monitoringfamily_r7insightops_forward_gh_ghipss_errorlog_name }}",
        enabled: "true",
        name: "{{ monitoringfamily_r7insightops_forward_gh_ghipss_errorlog_name }}",
        path: "{{ local_vars_proxy_forward_gh_ghipss_log_error_file }}"
    }
monitoringfamily_r7insightops_agent_restart_enabled: true    