---
proxy_zwcellulant_vhost_file: "forward_zwcellulant.conf"
zwcellulant_upstream_host1: "197.159.96.35:9009"
zwcellulant_upstream_host1_mon_type: tcp
zwcellulant_upstream_host1_mon_scheme: http
zwcellulant_upstream_host2: "197.159.96.35:8080"
zwcellulant_upstream_host2_mon_type: tcp
zwcellulant_upstream_host2_mon_scheme: http
webserverfamily_nginx_ppa_version_enable: true
webserverfamily_nginx_enable: true
webserverfamily_nginx_install_details:
  - nginx
  - nginx-extras
webserverfamily_nginx_push_configfiles_details:
  forward_zwcellulant:
    src: "nginx/_generic_vhost.conf.j2"
    dest: "/etc/nginx/sites-available/{{ proxy_zwcellulant_vhost_file }}"
    owner: "root"
    group: "root"
    port: "{{ global_zwcellulant_nginx_port }}"
    ssl_enabled: false
    domain_names:
      - "localhost"
    logging_enabled: true
    access_log_file: "/var/log/nginx/forward_zwcellulant_nginx_proxy_access.log"
    access_format: "jsonlog"
    error_log_file: "/var/log/nginx/forward_zwcellulant_nginx_proxy_error.log"
    locations:
      - context: "/test"
        instructions:
          - "access_log off"
          - "return 200"
      - context: "/payment/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ zwcellulant_upstream_host1_mon_scheme }}://{{ zwcellulant_upstream_host1 }}/"
      - context: "/lookup/"
        instructions:
          - "proxy_set_header X-Forwarded-For $server_addr"
          - "proxy_pass {{ zwcellulant_upstream_host2_mon_scheme }}://{{ zwcellulant_upstream_host2 }}/"
webserverfamily_nginx_deletefiles_details:
  - "/etc/nginx/sites-enabled/default"
webserverfamily_nginx_common_enable_sites_details_hash:
  zwcellulant:
    vhost: "{{ proxy_zwcellulant_vhost_file }}"
webserverfamily_nginx_common_validation_enable: true
webserverfamily_nginx_common_restart_enabled: true
elasticbeats_configuration_details:
  zwcellulant:
      src: "monitor.yml.j2"
      dest: "/etc/heartbeat/monitors.d/zwcellulant.yml"
      type: "{{ zwcellulant_upstream_host1_mon_type }}"
      name: "zwcellulant"
      enabled: true
      schedule: "@every 30s"
      hosts: ["{{zwcellulant_upstream_host1}}","{{ zwcellulant_upstream_host2 }}"]
elasticbeats_systemd_details: 
  restart:
      name: "heartbeat-elastic"
      state: "restarted"
elk_instance_name: "{{ hostvars[inventory_hostname]['ec2_placement'] }}"